In [1]:
import pandas as pd
import numpy as np

from pandas import DataFrame
from pandas import Series

<h1 style = "color:blue"> Data Cleaning And Wraggling </h1>

<div style = "background-color:lightblue; color:green">Data cleaning referes to process of fixing or removing incorrect, inconsistent, imcomplete or duplicate data. Data Wraggling is broader terms that refere to data cleaning as well as transforming it into usable form.

<h1 style = "color:blue">Data Cleaning

<h2 style = "color:blue">1. Handaling Missing Data</h2>

<h3 style = "color:blue">Using dropna</h3>

In [4]:
data = pd.read_csv('/home/kartika/Downloads/people_data.csv')
data

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

In [85]:
data.dropna(axis = 1) # or axis = 0

  First Name Last Name
0     Shelby   Terrell
1    Phillip   Summers
2   Kristine    Travis
3    Yesenia  Martinez
4       Lori      Todd

<div style="color:green; background-color:lightblue">dropna removes the rows or column with missing values.</div>

In [86]:
data.dropna(how = 'any')

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher

In [87]:
data.dropna(how = 'all')

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">how parameter takes two arguments any and all. If passed 'any' then removes row with atleast one missing values, if passed all then removes row with all missing values.

In [88]:
data.dropna(subset=['Sex'])

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">subset parameter removes missing value along a particular column.

In [91]:
# data.dropna(inplace = True)
# data

<div style="color:green; background-color:lightblue">inplace parameter removes missing values and modifies the original data. It is normally used when there is memory or storage constraints.

In [102]:
data.dropna(thresh = 5)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher

<div style="color:green; background-color:lightblue">thresh parameter specifies the minimum number of non missing values required to keep any row or column. The row or column with non missing values less than thresh value will be dropped.

<h3 style = "color:blue">Using fillna</h3>

In [103]:
data

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

In [106]:
data.fillna('kar') # or any number

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,kar,Phytotherapist
2,Kristine,Travis,kar,bthompson@example.com,1992-07-02,kar
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,kar,kar,Veterinary surgeon

<div style="color:green; background-color:lightblue">fillna can be used to fill the missing value with other values.

In [107]:
data.fillna({'Date of birth':'Replacing Birth'})

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,Replacing Birth,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,Replacing Birth,Veterinary surgeon

<div style="color:green; background-color:lightblue">We can use a dictionary to fill missing value along a particular column.

In [108]:
data.ffill()

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1945-10-26,Phytotherapist
2,Kristine,Travis,Female,bthompson@example.com,1992-07-02,Phytotherapist
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,kaitlinkaiser@example.com,2017-08-03,Veterinary surgeon

In [109]:
data.bfill()

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1992-07-02,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Market researcher
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">ffill method fills the missing value with previous known data, whereas bfill fills the missing value with next known data. ffill and bfill normally works along a column, it can be changed by passing axis = 1 parameter.

In [111]:
data.fillna(1000, limit = 1)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1000,Phytotherapist
2,Kristine,Travis,1000,bthompson@example.com,1992-07-02,1000
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,1000,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue"> limit parameter specifies limit for filling the missing values.

<h3 style = "color:blue"> Using Replace </h3>

In [5]:
data

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

In [115]:
data.replace('Male','M')

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,M,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,M,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,M,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">replace can be used to replace any of the values in the dataset with other values.

In [119]:
data.replace(['Shelby','Phillip'],'Names')

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Names,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Names,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">Multilple values can be replaced with a single value.

In [121]:
data.replace('[A-Za-z]','o', regex = True)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,oooooo,ooooooo,oooo,oooooo57@ooooooo.ooo,1945-10-26,ooooo ooooooooo
1,ooooooo,ooooooo,oooooo,ooooooo14@ooooooo.ooo,NaN,oooooooooooooo
2,oooooooo,oooooo,NaN,ooooooooo@ooooooo.ooo,1992-07-02,NaN
3,ooooooo,oooooooo,oooo,ooooooooooooo@ooooooo.ooo,2017-08-03,oooooo oooooooooo
4,oooo,oooo,oooo,NaN,NaN,oooooooooo ooooooo

<div style="color:green; background-color:lightblue">In this way we can replace entire alphabetical values with any other value.

In [127]:
data.replace('[0-9]','10000', regex = True)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah1000010000@example.net,10000100001000010000-1000010000-1000010000,Games developer
1,Phillip,Summers,Female,bethany1000010000@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,10000100001000010000-1000010000-1000010000,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,10000100001000010000-1000010000-1000010000,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">Similar operation can be performed for number as well.

In [6]:
data.replace({'Last Name':'[A-Z]'},'Names', regex = True)   #data['Last Name'].str.replace('Names')

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Nameserrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Namesummers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Namesravis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Namesartinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Namesodd,Male,NaN,NaN,Veterinary surgeon

<div style="color:green; background-color:lightblue">In this way values can be replaced along a particular column using dictionary and regex.

<div style="color:green; background-color:lightblue">regex set as True is used when replacing values based on matching or based on start and end character, A-Z in this context.

<h3 style = "color:blue">Using Interpolate</h3>

In [142]:
dataa = DataFrame({'First':[2,5,2,np.nan,2],
                   'Second':[np.nan,2,7,2,3],
                   'Third':[4,5,2,np.nan,np.nan],
                   'Fourth':[np.nan,2,7,3,4]}, index = list('abcde'))
print(dataa)

   First  Second  Third  Fourth
a    2.0     NaN    4.0     NaN
b    5.0     2.0    5.0     2.0
c    2.0     7.0    2.0     7.0
d    NaN     2.0    NaN     3.0
e    2.0     3.0    NaN     4.0

In [143]:
dataa.interpolate()

   First  Second  Third  Fourth
a    2.0     NaN    4.0     NaN
b    5.0     2.0    5.0     2.0
c    2.0     7.0    2.0     7.0
d    2.0     2.0    2.0     3.0
e    2.0     3.0    2.0     4.0

<div style="color:green; background-color:lightblue">interpolate fills missing values based on surrounding values. It is only applicable for numbers.

In [148]:
dataa.interpolate(method = 'linear',axis = 1)

   First  Second  Third  Fourth
a    2.0     3.0    4.0     4.0
b    5.0     2.0    5.0     2.0
c    2.0     7.0    2.0     7.0
d    NaN     2.0    2.5     3.0
e    2.0     3.0    3.5     4.0

<div style="color:green; background-color:lightblue">interpolate fills missing value along a column if both upper and lower values are present. It fills missing value along a row if both left and right values are present.

In [150]:
dataa.interpolate(limit_direction = 'forward',limit = 2)

   First  Second  Third  Fourth
a    2.0     NaN    4.0     NaN
b    5.0     2.0    5.0     2.0
c    2.0     7.0    2.0     7.0
d    2.0     2.0    2.0     3.0
e    2.0     3.0    2.0     4.0

<div style="color:green; background-color:lightblue">limit paramter sepcifies the minium number of values to be filled either backward or forward or both.

<h2 style = "color:blue">2.Data Transformation</h2>

<h3 style ="color:blue">Removing Duplicate Data</h3>

In [156]:
df = DataFrame({'First':[1,3,2,3,2],'Second':[3,2,2,2,5]})
df

   First  Second
0      1       3
1      3       2
2      2       2
3      3       2
4      2       5

In [157]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

<div style="color:green; background-color:lightblue">.duplicated() returs a series of boolean values showing the presence of duplicate row. The row is duplicate if all the column values across that row is same with any previous row.

In [159]:
df.drop_duplicates()

   First  Second
0      1       3
1      3       2
2      2       2
4      2       5

<div style="color:green; background-color:lightblue">.drop_duplicates returns new dataframe removing the duplicate row.

In [160]:
df.drop_duplicates(subset = ['First'])

   First  Second
0      1       3
1      3       2
2      2       2

<div style="color:green; background-color:lightblue">By default .drop_duplicates consider all the column values. We can use subset parameter to detect duplicates along a specific column.

In [161]:
df.drop_duplicates(keep = 'last')

   First  Second
0      1       3
2      2       2
3      3       2
4      2       5

<div style="color:green; background-color:lightblue">.drop_duplicates preserves the first observed row and removes other duplicates. Passing keep = 'last' parameter does the opposite.

<h3 style = "color:blue">Transformation Using Function or Mapping</h3>

In [174]:
df = DataFrame({'Salesman':['Salesman1','Salesman2','Salesman3','Salesman4','Salesman5'],
                'Sales':[17,30,28,15,34]})
df

    Salesman  Sales
0  Salesman1     17
1  Salesman2     30
2  Salesman3     28
3  Salesman4     15
4  Salesman5     34

In [177]:
dic = {
    'Salesman1':'Company1',
    'Salesman2':'Company2',
    'Salesman3':'Company3',
    'Salesman4':'Company4',
'Salesman5':'Company5'}
# df['Company'] = df['Salesman'].map(dic)
df

    Salesman  Sales
0  Salesman1     17
1  Salesman2     30
2  Salesman3     28
3  Salesman4     15
4  Salesman5     34

In [178]:
def Company(x):
    return dic[x]

df['Company'] = df['Salesman'].map(Company)
df

    Salesman  Sales   Company
0  Salesman1     17  Company1
1  Salesman2     30  Company2
2  Salesman3     28  Company3
3  Salesman4     15  Company4
4  Salesman5     34  Company5

<div style="color:green; background-color:lightblue">In this way we can transform dataframe using function mapping.

<h3 style = "color:blue"> Renaming Axis Indexes</h3>

In [189]:
data = DataFrame(np.arange(12).reshape(4,3), index = ['first','second','third','fourth'], columns = ['column1','column2','column3'])
data

        column1  column2  column3
first         0        1        2
second        3        4        5
third         6        7        8
fourth        9       10       11

In [190]:
def mod(x):
     return x.upper()
data.index = data.index.map(mod)
data

        column1  column2  column3
FIRST         0        1        2
SECOND        3        4        5
THIRD         6        7        8
FOURTH        9       10       11

<div style="color:green; background-color:lightblue">In this way we can even transform axis indexes of data as well using function and mapping.
If we just want the transformed version of data without actually modifying the actual data, rename method can be used.

In [194]:
data.rename(index = str.title,columns = str.upper)

        COLUMN1  COLUMN2  COLUMN3
First         0        1        2
Second        3        4        5
Third         6        7        8
Fourth        9       10       11

<h3 style = "color:blue">Discretization and Binning
</h3>

<div style="color:green; background-color:lightblue">Discrete data can only take specific, seperate values.<br>
It usually takes integer value.<br>
It is usually counted.<br>
For example: Number of students per class = [40,33,25]

<div style="color:green; background-color:lightblue">Continuous data can take any values within a range.<br>
It can take decimals, fractions.<br>
It is usually measured.<br>
For example: Height of Plants = [3.4,5.6,4,4]

<div style="color:green; background-color:lightblue">Binning is the process of grouping continuous numeric data into discrete categories for analysis.

In [221]:
ages = Series([12,75,13,59,34,23,75,23,33,83,23])

bins = [18,25,40,60,80]
age_category = pd.cut(ages,bins,right = False)  # By default intervals are (], left is exclusive and right is inclusive
age_category

0              NaN
1     [60.0, 80.0)
2              NaN
3     [40.0, 60.0)
4     [25.0, 40.0)
5     [18.0, 25.0)
6     [60.0, 80.0)
7     [18.0, 25.0)
8     [25.0, 40.0)
9              NaN
10    [18.0, 25.0)
dtype: category
Categories (4, interval[int64, left]): [[18, 25) < [25, 40) < [40, 60) < [60, 80)]

<div style="color:green; background-color:lightblue">pd.cut can be used to group continous data into discrete category.

In [222]:
age_category.value_counts()

[18, 25)    3
[25, 40)    2
[60, 80)    2
[40, 60)    1
Name: count, dtype: int64

In [224]:
group_names = ['Young','Adult','Middle Aged','Senior']
pd.cut(ages, bins, labels = group_names)

0             NaN
1          Senior
2             NaN
3     Middle Aged
4           Adult
5           Young
6          Senior
7           Young
8           Adult
9             NaN
10          Young
dtype: category
Categories (4, object): ['Young' < 'Adult' < 'Middle Aged' < 'Senior']

<div style="color:green; background-color:lightblue">The numeric intervals can be labeled as various ways by passing list of new labels in labels parameter.

In [227]:
pd.cut(ages,4,precision = 2) # precision = 2 limits the decimal value upto two digits

0     (11.93, 29.75]
1      (65.25, 83.0]
2     (11.93, 29.75]
3      (47.5, 65.25]
4      (29.75, 47.5]
5     (11.93, 29.75]
6      (65.25, 83.0]
7     (11.93, 29.75]
8      (29.75, 47.5]
9      (65.25, 83.0]
10    (11.93, 29.75]
dtype: category
Categories (4, interval[float64, right]): [(11.93, 29.75] < (29.75, 47.5] < (47.5, 65.25] < (65.25, 83.0]]

<div style="color:green; background-color:lightblue">If any integer is passed , pandas automatically divides the whole data into equal width bins. It is calculated by using maximum and minimum value from the data giving us less control compared to explicitly defining and passing bin width.

In [233]:
q=pd.qcut(ages,4, precision = 2)
q.value_counts()

(11.99, 23.0]    5
(67.0, 83.0]     3
(33.0, 67.0]     2
(23.0, 33.0]     1
Name: count, dtype: int64

<div style="color:green; background-color:lightblue">pd.cut() divides the data into equal width bins, whereas pd.qcut() divides data into equal size bins.

<h3 style = "color:blue">Detecting and Filtering Outliers

<div style="color:green; background-color:lightblue">Outliers are extreme or abnormal values that can distort analysis and summaries.<br>

In [4]:
data = DataFrame(np.random.randn(1000,4))  # or np.random.standard_normal(size) gives normally distributed data
data

            0         1         2         3
0    0.518634 -0.914222  0.277743 -0.319527
1    0.183156 -1.702650  1.245018 -0.764219
2   -0.126119  0.608423  0.105132  0.691134
3   -1.728373  0.680469  0.217000  0.003566
4    0.153292  0.962619 -0.423433  0.927461
..        ...       ...       ...       ...
995 -0.257433  0.598740  0.671771  0.213723
996 -0.795659 -0.031118  1.499319 -1.505513
997  1.190480  0.948139  0.237446  0.598738
998  0.007693  0.812684  1.747943 -0.298752
999 -0.326511  0.745750 -1.792031 -0.733317

[1000 rows x 4 columns]

In [20]:
data[(data.abs() > 3).any(axis = 1)]

            0         1         2         3
171  3.107579  0.372555  2.244835 -0.567795
318 -0.444392 -0.170547  1.269797  3.162948
425  0.948364  0.491268  3.230403 -0.919615
427  2.227344 -0.344617  0.592552  3.264123
619  0.042186  2.421696 -0.684023 -3.023543
824  0.161326  0.256419  3.494462  0.620418
887  3.290570 -0.599932 -0.162119 -2.526899
991  0.291836  1.506241 -0.986424 -3.453971

<div style="color:green; background-color:lightblue">This is how we can filter extreme values exceeding |3| from the dataframe.

<h3 style = "color:blue">Permutation and Random Sampling</h3>

<div style="color:green; background-color:lightblue">We can randomly reorder series or rows in dataframe using numpy random.permutation function.

In [24]:
df = DataFrame(np.random.randint(1,100,(4,5)), index = list('abcd'), columns = list('ABCDE'))
df

    A   B   C   D   E
a  21  55  99  72  92
b  20  45   1  69  32
c  76  98  50  65  13
d  34  16   8  67  66

In [32]:
row_sampler = np.random.permutation(4)
row_sampler

array([3, 1, 0, 2])

In [33]:
df.take(row_sampler)

    A   B   C   D   E
d  34  16   8  67  66
b  20  45   1  69  32
a  21  55  99  72  92
c  76  98  50  65  13

<div style="color:green; background-color:lightblue">In this way we can create a random order sample using permutation method and change the order rows of dataframe. It is also possible for columns by passing axis = 'columns' parameter.

In [34]:
column_sampler = np.random.permutation(5)
column_sampler

array([1, 4, 2, 0, 3])

In [36]:
df.take(column_sampler, axis = 1)

    B   E   C   A   D
a  55  92  99  21  72
b  45  32   1  20  69
c  98  13  50  76  65
d  16  66   8  34  67

In [39]:
df.sample(2,axis = 1, replace = True)

    D   A
a  72  21
b  69  20
c  65  76
d  67  34

<div style="color:green; background-color:lightblue">We can also select random rows or columns using sample function. Passing replace = True allows to choose same rows or columns while sampling.

<h3 style = "color:blue">Computing Indicator / Dummy Variable</h3>

In [45]:
df = DataFrame({"Key":['a','d','b','a','d','c']})

df

  Key
0   a
1   d
2   b
3   a
4   d
5   c

In [48]:
pd.get_dummies(df['Key'], dtype = int, prefix = 'key')

   key_a  key_b  key_c  key_d
0      1      0      0      0
1      0      0      0      1
2      0      1      0      0
3      1      0      0      0
4      0      0      0      1
5      0      0      1      0

<div style="color:green; background-color:lightblue">pd.get_dummies function is used to convert categorical data to numeric form so that it can be use for analysis and machine learning models. If a particular column in dataframe has k distinct elements then pd.get_dummies creats a dataframe having k column consisting all 0s and 1s.

<h2 style = "color:blue">3. String Manipulation</h2>

In [20]:
val = 'pi, phi and e are numbers'
pieces = [ x.strip() for x in val.split(",")]
pieces

['pi', 'phi and e are numbers']

<div style="color:green; background-color:lightblue">Here python in-built string method split can be used to break string separated by comma,space or other delimiters and return a list of string pieces. strip()[lstrip() and rstrip()] method can be used to remove unwanted charater or new line from start or end of the string.

In [21]:
"|".join(pieces)

'pi|phi and e are numbers'

<div style="color:green; background-color:lightblue">Similary, now the broken string pieces can be joined by another delimiter using .join method.

In [22]:
val.replace(",","|")

'pi| phi and e are numbers'

<div style="color:green; background-color:lightblue">Another common method is using replace as discussed above.

In [24]:
val.upper()

'PI, PHI AND E ARE NUMBERS'

In [25]:
val.lower()

'pi, phi and e are numbers'

<div style="color:green; background-color:lightblue">.upper() and .lower() method can be used to capatilized and convert string to lowercase respectively.

In [29]:
val.index('phi')

4

In [30]:
val.find('phi')

4

<div style="color:green; background-color:lightblue">.index and .find both can be used to get the index/position of first character of first occurence substring. The only difference is that .index throws an error if the substring is not found, whereas .find returns -1 without crashing our program.

<h3 style = "color:blue">Regular Expression (regex)</h3>

In [16]:
import re

<div style="color:green; background-color:lightblue">Regular Expression (regex) is a pattern used to search, match, extract or replace complex string patterns in text.

<div style="color:green; background-color:lightblue">patters are normally written as raw string that treats \ as literal character rather than an escape character.

In [5]:
csv = pd.read_csv('/home/kartika/Downloads/people_data.csv')
csv

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

In [30]:
text = '''Shelby	Terrell	Male	elijah57@example.net	1945-10-26	Games developer
	Phillip	Summers	Female	bethany14@example.com	NaN	Phytotherapist
	Kristine	Travis	NaN	bthompson@example.com	1992-07-02	NaN
	Yesenia	Martinez	Male	kaitlinkaiser@example.com	2017-08-03	Market researcher
	Lori	Todd	Male	NaN	NaN	Veterinary surgeon'''

In [28]:
pattern = r"\d{4}-\d{2}-\d{2}"
regex = re.compile(pattern)

# matches = re.findall(pattern,text)
#matches
print(regex.findall(text))
print(regex.search(text))
print(regex.match(text))

['1945-10-26', '1992-07-02', '2017-08-03']
<re.Match object; span=(41, 51), match='1945-10-26'>
None

<div style="color:green; background-color:lightblue">First we can create a pattern using raw string and regex tokens that can be compiled by re module and use to find pattern in text. .findall function can be used to search all the patterns matching regex. search only returns the first occurence of pattern and match returns if pattern appears at the beginning of the string.

<div style="color:green; background-color:lightblue">It is recommended to use re.compile to create regex object of the pattern to be used multiple time as it improves readibility and performance.<br>
As the pattern/regex is compiled first and then only other re functions are used. So when same regex is being used multiple time, it is better to create object of it using re.compile.

In [32]:
email_pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regex = re.compile(email_pattern, flags = re.IGNORECASE)

regex.findall(text)

['elijah57@example.net',
 'bethany14@example.com',
 'bthompson@example.com',
 'kaitlinkaiser@example.com']

<div style="color:green; background-color:lightblue">Suppose we want to extract name, domain name from the email. We can seperate each component , () can be use for each pattern.

In [34]:
regex = re.compile(r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})", flags = re.IGNORECASE)
regex.findall(text)

[('elijah57', 'example', 'net'),
 ('bethany14', 'example', 'com'),
 ('bthompson', 'example', 'com'),
 ('kaitlinkaiser', 'example', 'com')]

<h3 style = "color:blue">String Functions in Pandas</h3>

<div style="color:green; background-color:lightblue">String Manipulation in pandas can be done using vectorized string method accessed via .str.<br>
Pandas string works on one value at a time, whereas pandas works on entire series. <br>
Using .str gives fast and vectorized operation.

In [19]:
series = Series(['Alpha','Beta','Gamma'])
series

0    Alpha
1     Beta
2    Gamma
dtype: object

In [22]:
# series.upper()  Throws error
series.str.upper()

0    ALPHA
1     BETA
2    GAMMA
dtype: object

In [23]:
series.str[:2]

0    Al
1    Be
2    Ga
dtype: object

<div style="color:green; background-color:lightblue">..str can be used to slice through the string on entire series.

In [31]:
s = Series(['a,c','d'])
s

0    a,c
1      d
dtype: object

In [37]:
s.str.split(",", expand = True)[0]

0    a
1    d
Name: 0, dtype: object

In [38]:
csv

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,NaN,Phytotherapist
2,Kristine,Travis,NaN,bthompson@example.com,1992-07-02,NaN
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,NaN,NaN,Veterinary surgeon

In [39]:
csv['Email'].str.contains('com')

0    False
1     True
2     True
3     True
4      NaN
Name: Email, dtype: object

In [40]:
csv['Email'].str.replace('com','net')

0         elijah57@example.net
1        bethany14@example.net
2        bthompson@example.net
3    kaitlinkaiser@example.net
4                          NaN
Name: Email, dtype: object

<h3 style = "color:blue">Categorical Data</h3>

<div style="color:green; background-color:lightblue">Categorical Data(Qualitative data) represents variables that takes data under a specific category or label. Arithmetic operations are not performed with categorical data.<br>
For example:<br>
The number of students from section A-G<br>
The labels A-G represents categorical data whereas, the actual number of students represents discrete data.

In [52]:
values = Series(['Alpha','Beta','Gamma']*2)
values

0    Alpha
1     Beta
2    Gamma
3    Alpha
4     Beta
5    Gamma
dtype: object

In [53]:
pd.unique(values)

array(['Alpha', 'Beta', 'Gamma'], dtype=object)

In [54]:
values.value_counts()

Alpha    2
Beta     2
Gamma    2
Name: count, dtype: int64

In [81]:
values = values.astype('category')
values
# values = pd.Categorical(values)

['Alpha', 'Beta', 'Gamma', 'Alpha', 'Beta', 'Gamma']
Categories (3, object): ['Alpha', 'Beta', 'Gamma']

In [85]:
codes = values.codes
codes

array([0, 1, 2, 0, 1, 2], dtype=int8)

<div style="color:green; background-color:lightblue">codes method returns series of integers according to occurence of values in categorical data.

In [86]:
category = pd.Categorical(['Alpha','Gamma','Theta'])
codes = [0,0,1,2,1,2,2,2]

values = pd.Categorical.from_codes(codes,category)

In [87]:
values

['Alpha', 'Alpha', 'Gamma', 'Theta', 'Gamma', 'Theta', 'Theta', 'Theta']
Categories (3, object): ['Alpha', 'Gamma', 'Theta']

<div style="color:green; background-color:lightblue">The categorical data can be reterived from the general category and the values of occurence from the codes.

In [9]:
data = np.random.standard_normal(10)
data

array([-1.93285909, -1.61555989, -0.78215332, -1.79610551, -1.19985109,
       -0.41895967, -0.76635885, -0.0390223 , -0.77337857,  1.94275837])

In [14]:
bins = pd.qcut(data,4, labels = ['Group A','Group B','Group C','Group D'])
bins

['Group A', 'Group A', 'Group B', 'Group A', 'Group B', 'Group D', 'Group C', 'Group D', 'Group C', 'Group D']
Categories (4, object): ['Group A' < 'Group B' < 'Group C' < 'Group D']

In [16]:
bins.codes

array([0, 0, 1, 0, 1, 3, 2, 3, 2, 3], dtype=int8)

<div style = "background-color:white"></div>

<h1 style = "color:blue">Data Wraggling
</h1>

In [1]:
import pandas as pd
import numpy as np

from pandas import Series
from pandas import DataFrame

<h2 style = "color:blue">1. Hierarchial Indexing</h1>

<div style="color:green; background-color:lightblue">Hierarchial indexing is feature of pandas that allows to have two or more indexes on axes.

In [7]:
series = Series(np.random.standard_normal(8), index = [['a','a','b','b','c','c','d','d'],np.arange(1,9)])
series

a  1    1.744033
   2   -0.731710
b  3    2.641792
   4    0.691735
c  5    0.824614
   6   -0.360333
d  7    1.190344
   8   -0.521600
dtype: float64

In [8]:
series.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 3),
            ('b', 4),
            ('c', 5),
            ('c', 6),
            ('d', 7),
            ('d', 8)],
           )

In [11]:
series.loc['c']

5    0.824614
6   -0.360333
dtype: float64

In [16]:
series.unstack()    #series.unstack().stack()  To reverse

          1        2         3         4         5         6         7       8
a  1.744033 -0.73171       NaN       NaN       NaN       NaN       NaN     NaN
b       NaN      NaN  2.641792  0.691735       NaN       NaN       NaN     NaN
c       NaN      NaN       NaN       NaN  0.824614 -0.360333       NaN     NaN
d       NaN      NaN       NaN       NaN       NaN       NaN  1.190344 -0.5216

<div style="color:green; background-color:lightblue">The series with multiple index can be converted to data frame using stack().

In [42]:
frame = DataFrame(np.arange(12).reshape(4,3), index = [['a','a','b','b'],[1,2,3,4]], columns = [['First','Second','First'],['GroupA','GroupB','GroupB']])
frame

     First Second  First
    GroupA GroupB GroupB
a 1      0      1      2
  2      3      4      5
b 3      6      7      8
  4      9     10     11

In [43]:
frame.index.names = ['First RowIndex','Second RowIndex']

frame.columns.names = ['MegaRank','MegaGroup']
frame

MegaRank                        First Second  First
MegaGroup                      GroupA GroupB GroupB
First RowIndex Second RowIndex
a              1                    0      1      2
               2                    3      4      5
b              3                    6      7      8
               4                    9     10     11

In [44]:
frame.loc['b']

MegaRank         First Second  First
MegaGroup       GroupA GroupB GroupB
Second RowIndex
3                    6      7      8
4                    9     10     11

In [45]:
frame.loc[:,'First']

MegaGroup                       GroupA  GroupB
First RowIndex Second RowIndex
a              1                     0       2
               2                     3       5
b              3                     6       8
               4                     9      11

<div style="color:green; background-color:lightblue">In this way multiple indexes can be used on axes of series and dataframe to work on multiple levels of data.

In [50]:
frame.swaplevel('MegaRank','MegaGroup', axis = 1)

MegaGroup                      GroupA GroupB
MegaRank                        First Second First
First RowIndex Second RowIndex
a              1                    0      1     2
               2                    3      4     5
b              3                    6      7     8
               4                    9     10    11

<div style="color:green; background-color:lightblue">Here swaplevel method can be used to swap the level of particular axis.

In [53]:
frame.sort_index(level = 1, axis = 1)

MegaRank                        First        Second
MegaGroup                      GroupA GroupB GroupB
First RowIndex Second RowIndex
a              1                    0      2      1
               2                    3      5      4
b              3                    6      8      7
               4                    9     11     10

<div style="color:green; background-color:lightblue">sort_index by default sorts all the level of index. Particular level of index can be sorted by passing level parameter.

In [59]:
frame1 = DataFrame({'a':np.arange(6),
                    'b':np.arange(6,12),
                    'c':np.arange(12,18)})
frame1

   a   b   c
0  0   6  12
1  1   7  13
2  2   8  14
3  3   9  15
4  4  10  16
5  5  11  17

In [64]:
frame2 = frame1.set_index(['b'])  #frame2.reset_index() to reset the indexing
frame2

    a   c
b
6   0  12
7   1  13
8   2  14
9   3  15
10  4  16
11  5  17

In [65]:
frame3 = frame1.set_index(['b'], drop = False)
frame3

    a   b   c
b
6   0   6  12
7   1   7  13
8   2   8  14
9   3   9  15
10  4  10  16
11  5  11  17

<div style="color:green; background-color:lightblue">In this way we can set any of the column as index of the dataframe. By default the index column is removed and set as index, which can be preserved by passing drop = False.

In [66]:
frame3

    a   b   c
b
6   0   6  12
7   1   7  13
8   2   8  14
9   3   9  15
10  4  10  16
11  5  11  17

In [68]:
frame3.columns = frame3.iloc[1]
frame3

7   1   7   13
b
6    0   6  12
7    1   7  13
8    2   8  14
9    3   9  15
10   4  10  16
11   5  11  17

<div style="color:green; background-color:lightblue">Similarly, any particular row can be set as column header using iloc method .

<h2 style = "color:blue">2. Combining and Merginig Datasets</h2>

<h3 style = "color:blue">Using pd.merge</h3>

In [2]:
df1 = DataFrame({'key':list('aca'),
                 'values1':np.arange(3)})
df2 = DataFrame({'key':list('baccb'),
                 'values2':np.arange(8,13)})
pd.merge(df1,df2, on = 'key')

  key  values1  values2
0   a        0        9
1   c        1       10
2   c        1       11
3   a        2        9

<div style="color:green; background-color:lightblue">pd.merge joins datasets based on key columns (common column).<br>
on parameter specify the key column.<br> The resulting merged dataframe has common as well as repeated common rows.

In [95]:
pd.merge(df1,df2, how = 'right')

  key  values1  values2
0   b      NaN        8
1   a      0.0        9
2   a      2.0        9
3   c      1.0       10
4   c      1.0       11
5   b      NaN       12

In [102]:
pd.merge(df1,df2, how = 'left')

  key  values1  values2
0   a        0        9
1   c        1       10
2   c        1       11
3   a        2        9

<div style="color:green; background-color:lightblue"> how parameter takes two arguements namely right(all rows from right dataframe) and left(all rows from left dataframe) that specifies the type of join. Missing value while merging is represented by Nan.

In [105]:
pd.merge(df1,df2, how = 'outer', indicator = True) # defualt inner

  key  values1  values2      _merge
0   a      0.0        9        both
1   a      2.0        9        both
2   b      NaN        8  right_only
3   b      NaN       12  right_only
4   c      1.0       10        both
5   c      1.0       11        both

<div style="color:green; background-color:lightblue">Similarly, how parameter takes another two arguments namely inner(common rows only) and outer(rows from both dataframes).

In [116]:
df3 = DataFrame({'A':np.arange(5),'B':np.arange(5,10)})
df4 = DataFrame({'A':np.arange(4,9),'B':np.arange(15,20)})
pd.merge(df3,df4, left_index = True, right_index = True, suffixes = ('First','Second'))

   AFirst  BFirst  ASecond  BSecond
0       0       5        4       15
1       1       6        5       16
2       2       7        6       17
3       3       8        7       18
4       4       9        8       19

<div style="color:green; background-color:lightblue">In this way all the common columns in the dataframes can merged in single dataframe.

<h3 style = "color:blue"> Using join</h3>

In [13]:
df1 = DataFrame(np.arange(12).reshape(3,4), columns = list('ABCD'))
print(f"{df1}\n")

df2 = DataFrame(np.arange(12,24).reshape(3,4), columns = list('EFGH'))
print(df2)

df1.join(df2)

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

    E   F   G   H
0  12  13  14  15
1  16  17  18  19
2  20  21  22  23

   A  B   C   D   E   F   G   H
0  0  1   2   3  12  13  14  15
1  4  5   6   7  16  17  18  19
2  8  9  10  11  20  21  22  23

<div style="color:green; background-color:lightblue">join combines datasets based on common indexes. It is index focused.

<h3 style = "color:blue">Using pd.concat</h3>

In [17]:
sr1 = Series(np.arange(4))
sr2 = Series(np.arange(4,8))

pd.concat([sr1,sr2])

0    0
1    1
2    2
3    3
0    4
1    5
2    6
3    7
dtype: int64

<div style="color:green; background-color:lightblue">concat just combines(stacks) two datasets on the basis of row or column.

In [29]:
pd.concat([df1,df2], axis = 1, keys= ['First','Second'])

  First            Second
      A  B   C   D      E   F   G   H
0     0  1   2   3     12  13  14  15
1     4  5   6   7     16  17  18  19
2     8  9  10  11     20  21  22  23

<div style="color:green; background-color:lightblue">It is different from pd.merge as pd.merge based on key columns, whereas pd.concat just combines(stacks) datasets regardless of key columns.

In [21]:
pd.merge(df1,df2, left_index = True, right_index = True)

   A  B   C   D   E   F   G   H
0  0  1   2   3  12  13  14  15
1  4  5   6   7  16  17  18  19
2  8  9  10  11  20  21  22  23

<div style="color:green; background-color:lightblue">The given way can be also used, which is equivalent to pd.concat. Here, using pd.merge is safer as it allows more control from joining datasets, whereas concat just stacks datasets based on rows or columns.

In [27]:
pd.concat([df1,df2], join = 'inner')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 0, 1, 2]

<div style="color:green; background-color:lightblue">joint = 'inner' only joins common columns.

<h3 style = "color:blue">Using combine_first</h3>

In [31]:
df1 = DataFrame({'A':[3,52,2,np.nan,np.nan],'B':[np.nan,5,2,np.nan,5]})
df2 = DataFrame({'A':np.arange(5), 'B':np.arange(5,10)})

df1.combine_first(df2)

      A    B
0   3.0  5.0
1  52.0  5.0
2   2.0  2.0
3   3.0  8.0
4   4.0  5.0

<div style="color:green; background-color:lightblue">combine_first fills missing value in one dataset from another based on common columns.

<h2 style = "color:blue">3.Reshaping and Pivoting</h2>

In [13]:
df = DataFrame(np.random.randint(1,100,(3,4)), index = list('abc'), columns = ['First','Second','Third','Fourth'])
df

   First  Second  Third  Fourth
a     79      62     17      73
b     20      88     49      64
c     30      10     91      65

In [14]:
df.stack(level = 0)  #unstack() to reverse

a  First     79
   Second    62
   Third     17
   Fourth    73
b  First     20
   Second    88
   Third     49
   Fourth    64
c  First     30
   Second    10
   Third     91
   Fourth    65
dtype: int64

<div style="color:green; background-color:lightblue">stack pivots/rotates columns into rows.

<h3 style = "color:blue">Pivoting Long to Wide Format and Vice Versa</h3>

<div style="color:green; background-color:lightblue">In Wide Format, each variable has its seperate column and data is spread horizontally.<br>
In Long Format, one column stores variables and another stores values, and each row represent observation.

In [9]:
df = DataFrame({'product':['Table','Desk','Chair'],
                'width':[4,2,6],
                'height':[5,6,3],
                'length':[5,3,7]})
df

  product  width  height  length
0   Table      4       5       5
1    Desk      2       6       3
2   Chair      6       3       7

In [10]:
Long_format = df.melt(id_vars = ['product'],var_name = 'Variables',value_name = 'Value')
Long_format

  product Variables  Value
0   Table     width      4
1    Desk     width      2
2   Chair     width      6
3   Table    height      5
4    Desk    height      6
5   Chair    height      3
6   Table    length      5
7    Desk    length      3
8   Chair    length      7

<div style="color:green; background-color:lightblue">Wide format data can be converted to long format using pd.melt function.<br>
It has three parameters: id_vars: column to be fixed, var_name : column for variable and value_name: column for values.

In [16]:
wide_format = Long_format.pivot(index= ['product'],columns = 'Variables',values = 'Value')
wide_format

Variables  height  length  width
product
Chair           3       7      6
Desk            6       3      2
Table           5       5      4

<div style="color:green; background-color:lightblue">Long format data can be converted to wide format using pivot function.