<h1 style="color:blue">Data Aggregation and Group Operation</h1>

In [1]:
import numpy as np
import pandas as pd 

from pandas import Series
from pandas import DataFrame

<h1 style = "color:blue">Grouping

<div style="color:green; background-color:lightblue">Data aggregation refers to combining multiple values in single summary values.<br>
Data Aggregation is one of the part of Group Operation.

<div style="color:green; background-color:lightblue">Group operation refers to splitting data into parts, applying function to them and finally combining to get final result.<br>
Group aggregation : Split ---> Apply ----> Combine

In [3]:
df = DataFrame({'key1':list('abcedacd'),
                'key2':[1,2,3,2,1,1,3,2],

                'data1':np.random.randint(1,100,size=8),
                'data2':np.random.randint(1,100,size=8)})
print(df)

  key1  key2  data1  data2
0    a     1     89     20
1    b     2     19     65
2    c     3     58     51
3    e     2     38     19
4    d     1     51     52
5    a     1     96     81
6    c     3     59     88
7    d     2     55     27

In [5]:
groups = df.groupby('key1')
for x,y in groups:
    print(x,y)

a   key1  key2  data1  data2
0    a     1     89     20
5    a     1     96     81
b   key1  key2  data1  data2
1    b     2     19     65
c   key1  key2  data1  data2
2    c     3     58     51
6    c     3     59     88
d   key1  key2  data1  data2
4    d     1     51     52
7    d     2     55     27
e   key1  key2  data1  data2
3    e     2     38     19

In [15]:
groups.get_group('a')

  key1  key2  data1  data2
0    a     1     32     17
5    a     1     79     66

In [16]:
groups.size()

key1
a    2
b    1
c    2
d    2
e    1
dtype: int64

In [17]:
groups.count()

      key2  data1  data2
key1
a        2      2      2
b        1      1      1
c        2      2      2
d        2      2      2
e        1      1      1

<div style="color:green; background-color:lightblue">Groupby function can be used to split data into different groups using columns of dataframe.

In [4]:
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    55.5
b    25.0
c    19.5
d    72.5
e    70.0
Name: data1, dtype: float64

In [5]:
grouped = df['data1'].groupby(df['key2'])
grouped.mean()

key2
1    57.333333
2    59.666667
3    19.500000
Name: data1, dtype: float64

<div style="color:green; background-color:lightblue">This is one of the way by which we can calculate the mean of particular column using particular key label using groupby function.

In [6]:
means = df['data2'].groupby([df['key1'],df['key2']]).mean()
means

key1  key2
a     1       41.5
b     2       60.0
c     3       58.5
d     1       63.0
      2       70.0
e     2       64.0
Name: data2, dtype: float64

<div style="color:green; background-color:lightblue">The data can be grouped by passing multiple keys, resulting series with herirarchial indexing.

In [7]:
df.groupby('key1').mean()

      key2  data1  data2
key1
a      1.0   55.5   41.5
b      2.0   25.0   60.0
c      3.0   19.5   58.5
d      1.5   72.5   66.5
e      2.0   70.0   64.0

In [8]:
df.groupby(['key1','key2']).mean()

           data1  data2
key1 key2
a    1      55.5   41.5
b    2      25.0   60.0
c    3      19.5   58.5
d    1      61.0   63.0
     2      84.0   70.0
e    2      70.0   64.0

<div style="color:green; background-color:lightblue">In this way we can split entire dataframe into groups and apply function.

In [2]:
df = DataFrame(np.random.randint(1,100,size=(5,5)),columns = list('abcde'))
df

    a   b   c   d   e
0  94  42  62  34  90
1  46  68  27  97  37
2  96  65  31   7  31
3   3  92   2  13  28
4   9  11  66  94  95

In [37]:
mapping = {'a':'FirstSum',
           'b':'FirstSum',
           'c':'SecondSum',
           'd':'FirstSum',
           'e':'SecondSum'}

df.T.groupby(mapping).sum().T

   FirstSum  SecondSum
0       188        138
1       190         33
2       125        187
3        97         71
4       231          3

In [40]:
series = Series(mapping)
df.T.groupby(series).sum().T

   FirstSum  SecondSum
0       188        138
1       190         33
2       125        187
3        97         71
4       231          3

<div style="color:green; background-color:lightblue">In this way we can group data using dictionary and Series.
    . Note: Using axis = 1, with groupby function is depreciated in newer version, so transpose is used.

In [2]:
df = DataFrame({'Names':['Alpha','Beta','Theta','Gamma','Delta','Lambda']})
df

    Names
0   Alpha
1    Beta
2   Theta
3   Gamma
4   Delta
5  Lambda

In [13]:
group = df['Names'].groupby(df['Names'].str.len())
for x,y in group:
    print(x,y)

4 1    Beta
Name: Names, dtype: object
5 0    Alpha
2    Theta
3    Gamma
4    Delta
Name: Names, dtype: object
6 5    Lambda
Name: Names, dtype: object

<div style = "background-color:lightblue; color:green">In this way grouping can be done by passing functions as well.</div>

In [6]:
df = DataFrame(np.random.randint(1,100,size=(4,4)),index = [['a','b','a','b'],np.arange(4)])
df

      0   1   2   3
a 0  99  37  17  72
b 1  23  26  43  94
a 2  32  47  94  25
b 3  37   2  65   5

In [7]:
df.groupby(level=1).sum()

    0   1   2   3
0  99  37  17  72
1  23  26  43  94
2  32  47  94  25
3  37   2  65   5

<div style = "background-color:lightblue; color:green">Grouping can be done by heriarchal indexing as well.

In [2]:
df = DataFrame(np.random.randint(1,100,(4,5)))
print(df)

    0   1   2   3   4
0  30   7   1   8   4
1  23  75  38  83  99
2  61  60  73  76   9
3  30  37  41  59  98

<div></div>

<div></div>

<h2 style = "color:blue">Aggregating</h2>

In [16]:

group = df.groupby('key1')
for x,y in group:
    print(x,y)

a   key1  key2  data1  data2
0    a     1     89     20
5    a     1     96     81
b   key1  key2  data1  data2
1    b     2     19     65
c   key1  key2  data1  data2
2    c     3     58     51
6    c     3     59     88
d   key1  key2  data1  data2
4    d     1     51     52
7    d     2     55     27
e   key1  key2  data1  data2
3    e     2     38     19

In [18]:
agg = df.groupby('key1').agg({'data1':['min','max','sum']})
print(agg)

     data1
       min max  sum
key1
a       89  96  185
b       19  19   19
c       58  59  117
d       51  55  106
e       38  38   38

<div style = "background-color:lightblue; color:green">After grouping the dataframe using any column we can perform various aggregate functions on specific column in that grouped data.<br>
Using agg allows us to perform more than one aggregate function over grouped data.
</div>

In [6]:
data = {

    "Customer": np.random.choice(["Alice", "Bob", "Charlie", "David", "Eva"], 30),
    "City": np.random.choice(["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"], 30),
    "Product": np.random.choice(["Laptop", "Phone", "Tablet", "Headphones"], 30),
    "Category": np.random.choice(["Electronics", "Accessories"], 30),
    "Quantity": np.random.randint(1, 5, 30),
    "Price": np.random.randint(100, 1000, 30),
    
}
df = DataFrame(data)
print(df.head())

  Customer        City Product     Category  Quantity  Price
0    Alice  Biratnagar  Tablet  Electronics         3    804
1  Charlie  Biratnagar  Laptop  Accessories         3    700
2      Bob     Pokhara   Phone  Electronics         1    770
3    Alice     Pokhara   Phone  Electronics         4    570
4      Bob  Biratnagar   Phone  Accessories         1    985

In [23]:
print(df.groupby('City')['Price'].sum())

City
Biratnagar    6430
Kathmandu     1780
Lalitpur      1362
Pokhara       6795
Name: Price, dtype: int64

<div style = "background-color:lightblue; color:green">This calculates the total sales per city.</div>

In [24]:
print(df.groupby('Product')['Quantity'].sum())

Product
Headphones    18
Laptop        15
Phone         23
Tablet        26
Name: Quantity, dtype: int64

<div style = "background-color:lightblue; color:green">This calculates the total quantity sold per product.

In [ ]:
print(df.groupby('City')['Price'].agg(['mean','sum','min','max']))
#or df.groupby('City').agg({'Price':['mean','sum','min','max']})

                  mean   sum  min  max
City
Biratnagar  584.545455  6430  177  922
Kathmandu   445.000000  1780  207  848
Lalitpur    454.000000  1362  391  531
Pokhara     566.250000  6795  118  965

<div style = "background-color:lightblue; color:green">This calculates the sales statistics per city.

In [31]:
print(df.groupby(['City','Product'])['Price'].agg('sum'))

City        Product
Biratnagar  Headphones    1269
            Laptop        1118
            Phone          876
            Tablet        3167
Kathmandu   Laptop         932
            Phone          848
Lalitpur    Phone          831
            Tablet         531
Pokhara     Headphones    1958
            Laptop         118
            Phone         2776
            Tablet        1943
Name: Price, dtype: int64

<div style = "background-color:lightblue; color:green">This calculates total sales per city as well as per product.

 <h2 style = "color:blue">Transform

In [8]:
print(df.head())

  Customer        City Product     Category  Quantity  Price
0    Alice  Biratnagar  Tablet  Electronics         3    804
1  Charlie  Biratnagar  Laptop  Accessories         3    700
2      Bob     Pokhara   Phone  Electronics         1    770
3    Alice     Pokhara   Phone  Electronics         4    570
4      Bob  Biratnagar   Phone  Accessories         1    985

In [12]:
df["City_Avg_Revenue"] = df.groupby("City")["Price"].transform("mean")

In [11]:
print(df.head())

  Customer        City Product     Category  Quantity  Price  City_Avg_Revenue
0    Alice  Biratnagar  Tablet  Electronics         3    804        614.444444
1  Charlie  Biratnagar  Laptop  Accessories         3    700        614.444444
2      Bob     Pokhara   Phone  Electronics         1    770        693.888889
3    Alice     Pokhara   Phone  Electronics         4    570        693.888889
4      Bob  Biratnagar   Phone  Accessories         1    985        614.444444

<div style = "background-color:lightblue; color:green">transform() is used when performing aggregate function by grouping but keeping the original dataframe shape.<br>
It is useful when adding new column based group calculations.

<h2 style = "color:blue">Filtering

In [16]:
print(df.head())

  Customer        City Product     Category  Quantity  Price  City_Avg_Revenue
0    Alice  Biratnagar  Tablet  Electronics         3    804        614.444444
1  Charlie  Biratnagar  Laptop  Accessories         3    700        614.444444
2      Bob     Pokhara   Phone  Electronics         1    770        693.888889
3    Alice     Pokhara   Phone  Electronics         4    570        693.888889
4      Bob  Biratnagar   Phone  Accessories         1    985        614.444444

In [17]:
print(df.groupby('City').filter(lambda x: x['Price'].mean() > 500))

   Customer        City     Product     Category  Quantity  Price  \
0     Alice  Biratnagar      Tablet  Electronics         3    804
1   Charlie  Biratnagar      Laptop  Accessories         3    700
2       Bob     Pokhara       Phone  Electronics         1    770
3     Alice     Pokhara       Phone  Electronics         4    570
4       Bob  Biratnagar       Phone  Accessories         1    985
5   Charlie     Pokhara      Laptop  Electronics         3    302
6   Charlie    Lalitpur  Headphones  Electronics         2    863
7     David    Lalitpur       Phone  Accessories         3    640
8       Bob  Biratnagar       Phone  Accessories         1    162
9       Bob     Pokhara      Laptop  Accessories         3    738
10  Charlie  Biratnagar       Phone  Electronics         1    156
11  Charlie     Pokhara      Laptop  Accessories         3    971
12      Eva    Lalitpur      Laptop  Accessories         1    398
13    Alice     Pokhara       Phone  Accessories         3    536
14      Eva    Lalitpur       Phone  Electronics         1    829
15      Bob   Kathmandu      Laptop  Electronics         1    646
16      Eva     Pokhara      Tablet  Electronics         1    997
17    Alice  Biratnagar      Tablet  Electronics         2    863
18      Bob   Kathmandu      Tablet  Accessories         2    852
19  Charlie  Biratnagar       Phone  Electronics         4    363
20    Alice   Kathmandu      Laptop  Electronics         4    212
21      Bob   Kathmandu  Headphones  Electronics         2    621
22    David     Pokhara      Laptop  Accessories         1    390
23    David    Lalitpur  Headphones  Electronics         2    862
24    Alice     Pokhara       Phone  Electronics         1    971
25      Eva    Lalitpur       Phone  Accessories         4    671
26      Bob  Biratnagar  Headphones  Electronics         3    506
27  Charlie    Lalitpur      Laptop  Accessories         1    806
28      Bob  Biratnagar      Tablet  Accessories         1    991
29    David   Kathmandu      Laptop  Electronics         3    890

    City_Avg_Revenue
0         614.444444
1         614.444444
2         693.888889
3         693.888889
4         614.444444
5         693.888889
6         724.142857
7         724.142857
8         614.444444
9         693.888889
10        614.444444
11        693.888889
12        724.142857
13        693.888889
14        724.142857
15        644.200000
16        693.888889
17        614.444444
18        644.200000
19        614.444444
20        644.200000
21        644.200000
22        693.888889
23        724.142857
24        693.888889
25        724.142857
26        614.444444
27        724.142857
28        614.444444
29        644.200000

<div style = "background-color:lightblue; color:green">filter can be used to filter one or more rows from the grouped data based on the given condition.

<h2 style = "color:blue">Pivot Table

In [18]:
print(df.head())

  Customer        City Product     Category  Quantity  Price  City_Avg_Revenue
0    Alice  Biratnagar  Tablet  Electronics         3    804        614.444444
1  Charlie  Biratnagar  Laptop  Accessories         3    700        614.444444
2      Bob     Pokhara   Phone  Electronics         1    770        693.888889
3    Alice     Pokhara   Phone  Electronics         4    570        693.888889
4      Bob  Biratnagar   Phone  Accessories         1    985        614.444444

In [19]:
pd.pivot_table(
    df,
    values="City_Avg_Revenue",   # What to calculate
    index="City",       # Rows
    columns="Product",  # Columns
    aggfunc="sum"       # Operation
)

Product      Headphones       Laptop        Phone       Tablet
City
Biratnagar   614.444444   614.444444  2457.777778  1843.333333
Kathmandu    644.200000  1932.600000          NaN   644.200000
Lalitpur    1448.285714  1448.285714  2172.428571          NaN
Pokhara             NaN  2775.555556  2775.555556   693.888889

<div style = "background-color:lightblue; color:green">Pivot table is way of summarizing large datasets by transforming data from the original dataset by grouping and aggregating.

<div></div>

</div>

</div>

<h1 style = "color:blue">Time Series</h1>

<div style = "background-color:lightblue; color:green">Time series is simply sequence of observations(data points) indexed by time order.</div>

<div style = "background-color:lightblue; color:green">Types of time series data:<br>
1.Regualr Time series(Fixed Frequency Time series):<br>
Data is recorded at consistent, equally spaced time intervals.<br>
<br>
2.Irregular Time Series:<br>
Data is recorded at inconsistent, random time intervals.
<br>
<br>
3.Time-Stamped:<br>
Each value is tied to each time stamp.
<br>
<br>
4. Period Time Series:<br>
Data represents time span(intervals) instead of specific moment.

In [3]:
from datetime import datetime

In [6]:
now = datetime.now()
print(now)
print(f"{now.year},{now.month},{now.day},{now.hour},{now.minute},{now.second}")

2026-03-26 18:56:40.677946
2026,3,26,18,56,40

In [8]:
delta = datetime(2006, 10, 19) - now
print(delta)

-7099 days, 5:03:19.322054

In [17]:
string_date = "2024-06-01"
date_object = datetime.strptime(string_date, "%Y-%m-%d")
print(date_object)

dates = pd.to_datetime(["2024-01-01", "2025-01-02", "2023-12-31"], format = "%Y-%m-%d")
print(dates)

2024-06-01 00:00:00
DatetimeIndex(['2024-01-01', '2025-01-02', '2023-12-31'], dtype='datetime64[ns]', freq=None)

<div style = "background-color:lightblue; color:green">string date can be converted to datetime object using datetime.strptime and pd.to_datetime methods.<br><br>
pd.to_datetime is pandas way and more flexible as it converts list, series or column of string to datetime data.<br><br>
datetime.strptime is python way and converts string to datetime only one as time with strict format specifier.

<h2 style = "color:blue">Indexing, Selecting and Subsetting

In [22]:
time = pd.to_datetime([ '2023-12-31','2024-01-01', '2025-01-02'])
ts = Series(np.random.randint(1,100,3), index = time)
print(time)

DatetimeIndex(['2023-12-31', '2024-01-01', '2025-01-02'], dtype='datetime64[ns]', freq=None)

In [23]:
print(ts.index[1])
print(ts['2024-01-01'])
print(ts.iloc[0])

2024-01-01 00:00:00
65
35

In [24]:
print(ts['2024'])

2024-01-01    65
dtype: int64

In [25]:
print(ts["2023-01-01":"2025-01-02"])

2023-12-31    35
2024-01-01    65
2025-01-02    31
dtype: int64

<div style = "background-color:lightblue; color:green">Indexing and Slicing for time series can be done as normal pandas series. Also, since the time series is in chronogical order it can be indexed as range from start date to end date as shown in the above example.

<h2 style = "color:blue">Date Range, Frequencies and Shifting

In [31]:
date = pd.date_range('2026-03-01',datetime.now())
print(date)

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05', '2026-03-06', '2026-03-07', '2026-03-08',
               '2026-03-09', '2026-03-10', '2026-03-11', '2026-03-12',
               '2026-03-13', '2026-03-14', '2026-03-15', '2026-03-16',
               '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20',
               '2026-03-21', '2026-03-22', '2026-03-23', '2026-03-24',
               '2026-03-25', '2026-03-26', '2026-03-27'],
              dtype='datetime64[ns]', freq='D')

<div style = "background-color:lightblue; color:green">Here, pd.date_range() can be used to generate datetime index with particular length.

In [34]:
date = pd.date_range(start ='2026-03-01', periods = 10)
print(date)

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05', '2026-03-06', '2026-03-07', '2026-03-08',
               '2026-03-09', '2026-03-10'],
              dtype='datetime64[ns]', freq='D')

In [41]:
date = pd.date_range(end = '2026-03-01', periods = 10, freq = 'D')
print(date)

DatetimeIndex(['2026-02-20', '2026-02-21', '2026-02-22', '2026-02-23',
               '2026-02-24', '2026-02-25', '2026-02-26', '2026-02-27',
               '2026-02-28', '2026-03-01'],
              dtype='datetime64[ns]', freq='D')

<div style = "background-color:lightblue; color:green">We can also generate daily timestamp by passing start or end date and number of periods.<br>

In [43]:
print(pd.date_range(end = datetime.now(), periods = 10, freq ='h'))

DatetimeIndex(['2026-03-27 10:01:23.809344', '2026-03-27 11:01:23.809344',
               '2026-03-27 12:01:23.809344', '2026-03-27 13:01:23.809344',
               '2026-03-27 14:01:23.809344', '2026-03-27 15:01:23.809344',
               '2026-03-27 16:01:23.809344', '2026-03-27 17:01:23.809344',
               '2026-03-27 18:01:23.809344', '2026-03-27 19:01:23.809344'],
              dtype='datetime64[ns]', freq='h')

<div style = "background-color:lightblue; color:green">Frequencies denote how often date is recorded. There are different frequencies based on the need.

In [44]:
data = Series(np.random.randint(1,100,8), index = pd.date_range(end = datetime.now(),periods = 8))
print(data)

2026-03-20 19:06:13.804179    27
2026-03-21 19:06:13.804179    47
2026-03-22 19:06:13.804179     8
2026-03-23 19:06:13.804179    41
2026-03-24 19:06:13.804179    82
2026-03-25 19:06:13.804179     6
2026-03-26 19:06:13.804179    89
2026-03-27 19:06:13.804179     6
Freq: D, dtype: int64

In [46]:
data.shift(1, freq = 'D')

2026-03-21 19:06:13.804179    27
2026-03-22 19:06:13.804179    47
2026-03-23 19:06:13.804179     8
2026-03-24 19:06:13.804179    41
2026-03-25 19:06:13.804179    82
2026-03-26 19:06:13.804179     6
2026-03-27 19:06:13.804179    89
2026-03-28 19:06:13.804179     6
Freq: D, dtype: int64

<div style = "background-color:lightblue; color:green">Shifting refers to moving time up or down that is current time index is replaced by previos or next . It is useful in calculating change or growth rate.

In [47]:
print(data- data.shift(1))

2026-03-20 19:06:13.804179     NaN
2026-03-21 19:06:13.804179    20.0
2026-03-22 19:06:13.804179   -39.0
2026-03-23 19:06:13.804179    33.0
2026-03-24 19:06:13.804179    41.0
2026-03-25 19:06:13.804179   -76.0
2026-03-26 19:06:13.804179    83.0
2026-03-27 19:06:13.804179   -83.0
Freq: D, dtype: float64

In [48]:
print((data/data.shift(1))-1)

2026-03-20 19:06:13.804179          NaN
2026-03-21 19:06:13.804179     0.740741
2026-03-22 19:06:13.804179    -0.829787
2026-03-23 19:06:13.804179     4.125000
2026-03-24 19:06:13.804179     1.000000
2026-03-25 19:06:13.804179    -0.926829
2026-03-26 19:06:13.804179    13.833333
2026-03-27 19:06:13.804179    -0.932584
Freq: D, dtype: float64

<div style = "background-color:lightblue; color:green">In this way we can calculate change or growth rate on various frequencies using shifting.

<h2 style = "color:blue">Time Zone Handaling

<div style = "background-color:lightblue; color:green">Time zone defines the local time of a region.<br>
Coodinated Universal Time or UTC is geographycally independent standard time. Time zones are expressed as offset of UTC<br>
Kathmandu : UTC + 5:45
London : UTC + 0

In [4]:
import pytz

In [12]:
print(pd.Timestamp(datetime.now(),tz = "UTC"))

2026-03-28 14:56:12.913813+00:00

<div style = "background-color:lightblue; color:green">This is timezone awared datetime and mostly preferred during analysis.

In [13]:
data = Series(np.random.randint(1,100,6), index = pd.date_range(end = datetime.now(), periods = 6))
print(data)

2026-03-23 14:58:24.705326    69
2026-03-24 14:58:24.705326    80
2026-03-25 14:58:24.705326    30
2026-03-26 14:58:24.705326     2
2026-03-27 14:58:24.705326    63
2026-03-28 14:58:24.705326    71
Freq: D, dtype: int64

In [16]:
data = data.tz_localize('UTC')
print(data)

2026-03-23 14:58:24.705326+00:00    69
2026-03-24 14:58:24.705326+00:00    80
2026-03-25 14:58:24.705326+00:00    30
2026-03-26 14:58:24.705326+00:00     2
2026-03-27 14:58:24.705326+00:00    63
2026-03-28 14:58:24.705326+00:00    71
Freq: D, dtype: int64

<div style = "background-color:lightblue; color:green">In this way we can localize time using tz_localize method and passing 'UTC' method.<br>
Localizing assigns timezone to naive data (data having no timezone).

In [19]:
data1 = Series(np.random.randint(1,100,6), index = pd.date_range(end = datetime.now(), periods = 6))
data1 = data1.tz_localize('Asia/Kathmandu')
print(data1)

2026-03-23 15:11:32.331522+05:45    62
2026-03-24 15:11:32.331522+05:45    93
2026-03-25 15:11:32.331522+05:45    41
2026-03-26 15:11:32.331522+05:45    31
2026-03-27 15:11:32.331522+05:45    27
2026-03-28 15:11:32.331522+05:45    98
dtype: int64

In [20]:
data1 = data1.tz_convert('UTC')
print(data1)

2026-03-23 09:26:32.331522+00:00    62
2026-03-24 09:26:32.331522+00:00    93
2026-03-25 09:26:32.331522+00:00    41
2026-03-26 09:26:32.331522+00:00    31
2026-03-27 09:26:32.331522+00:00    27
2026-03-28 09:26:32.331522+00:00    98
dtype: int64


<div style = "background-color:lightblue; color:green">tz_localize assign timezone to data according to UTC or given region, whereas tz_convert timezone of given time awared data.

In [22]:
dates = pd.date_range('2024-01-01 00:00', periods=5, freq='h')

dates = dates.tz_localize('UTC')
print(dates)

DatetimeIndex(['2024-01-01 00:00:00+00:00', '2024-01-01 01:00:00+00:00',
               '2024-01-01 02:00:00+00:00', '2024-01-01 03:00:00+00:00',
               '2024-01-01 04:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='h')

In [25]:
# dates = dates.tz_convert('Asia/Kathmandu')
# print(dates)

<div style = "background-color:lightblue; color:green">This is the normal work while handaling timezone. First we got time navie data. We gave it time zone by localizing it with UTC and finally convert it to the timezone of Nepal.<br>
For time naive data we first localize and then convert. Directly converting time naive data throws error.

<h2 style = "color:blue">Periods and Period Arithmetic

<div style = "background-color:lightblue; color:green">Periods denote time span rather than specific moment.<br>
timestamp → 2024-01-01 10:00:00 (exact time)<br>
Period → 2024-01 (entire month)

In [26]:
periods = pd.period_range('2025-01',periods = 5, freq = 'M')
print(periods)

PeriodIndex(['2025-01', '2025-02', '2025-03', '2025-04', '2025-05'], dtype='period[M]')

<div style = "background-color:lightblue; color:green">In this way periods range can be declared. <br>It is different from date_range : pd.date_range('2024-01',periods = 5, freq = 'M') as internally it is treated as date time, but period is span not specific time.

In [29]:
periods = periods +1
print(periods)
periods = periods -1
print(periods)

PeriodIndex(['2025-02', '2025-03', '2025-04', '2025-05', '2025-06'], dtype='period[M]')
PeriodIndex(['2025-01', '2025-02', '2025-03', '2025-04', '2025-05'], dtype='period[M]')

<div style = "background-color:lightblue; color:green">Here periods arithmetic is similar to normal arithmetic. Adding or subtracting increase or decrease the span repectively.

In [34]:
period = pd.Period('2025-01', freq = 'M')
period = period.to_timestamp()
print(period)

2025-01-01 00:00:00

<div style = "background-color:lightblue; color:green">Here, periods can be converted to timestamp using to_timestamp method. You can clearly see the dtype for periods and datetime.

In [36]:
period = period.to_period(freq = 'M')
print(period)

2025-01

<div style = "background-color:lightblue; color:green">Similary, timestamp can be converted to period using to_period method.

<h2 style = "color:blue">Resampaling and Frequency Conversion

<div style = "background-color:lightblue; color:green">Resampaling refers to chainging the frequency of the given timeseries.

<div style = "background-color:lightblue; color:green">Downsampaling refers to converting high frequency to low frequency.<br>
Daily to Monthly<br>
Hourly to Daily

In [17]:
data = Series(np.random.randint(1,100,8), index = pd.date_range('2026-01-01',periods = 8, freq = 'D'))
print(data)

2026-01-01    57
2026-01-02    90
2026-01-03    32
2026-01-04    42
2026-01-05    10
2026-01-06    85
2026-01-07    39
2026-01-08    64
Freq: D, dtype: int64

In [21]:
print(data.resample('ME').mean())

2026-01-31    52.375
Freq: ME, dtype: float64

<div style = "background-color:lightblue; color:green">THe given timeseries has frequency of daily date. <br> 
We can resample it to monthly frequency using resample() method. Here, 'ME' stands for month end frequency. 
<br>Since we are resamplaing daily to monthly,  mean() function is used to calculate the average value for each month to avoid fluctuation.

<div style = "background-color:lightblue; color:green">Usamplaing refers to converting low frequency to high frequency.<br>
Daily to Hourly<br>
Montly to Daily

In [13]:
print(data.resample("h").ffill())

2026-01-01 00:00:00    11
2026-01-01 01:00:00    11
2026-01-01 02:00:00    11
2026-01-01 03:00:00    11
2026-01-01 04:00:00    11
                       ..
2026-01-07 20:00:00     5
2026-01-07 21:00:00     5
2026-01-07 22:00:00     5
2026-01-07 23:00:00     5
2026-01-08 00:00:00    51
Freq: h, Length: 169, dtype: int64

<div style = "background-color:lightblue; color:green">In this way we can convert low freq(daily) to high freq(hourly) using resample method. <br>
Since, upsampaling adds new timeslots some missing values are introduced which are handaled using fifill, bfill or interploate().

In [15]:
data1 = data.asfreq('D')
print(data1)

2026-01-01    11
2026-01-02    20
2026-01-03    72
2026-01-04    52
2026-01-05    80
2026-01-06    30
2026-01-07     5
2026-01-08    51
Freq: D, dtype: int64

<div style = "background-color:lightblue; color:green">asfreq simply converts the frequency of given timeseries. <br>
Unlike resample method that first group the given series and then use reduction function to give single value.

<h2 style = "color:blue">Moving Window Function

<div style = "background-color:lightblue; color:green">A moving window takes fixed-sized subset of data and applies function as it slides over time.<br>

In [37]:
data = Series([30,40,50,60,70])
print(data.rolling(window = 3).mean())

0     NaN
1     NaN
2    40.0
3    50.0
4    60.0
dtype: float64

<div style = "background-color:lightblue; color:green">windows:<br>
First two rows doesn't have enough data for window(3).<br>
[30,40,50]-mean<br>
[40,50,60]-mean<br>
[50,60,70]-mean

<div style = "background-color:lightblue; color:green">In the above example we got NaN in the first two rows, since no enough data for window(3). We can set the minimum number of data for window using min_periods parameter.

In [38]:
print(data.rolling(3, min_periods = 1).mean())

0    30.0
1    35.0
2    40.0
3    50.0
4    60.0
dtype: float64

In [42]:
time = Series(np.random.randint(1,100,5),index = pd.date_range('2024-01-01', periods = 5, freq = 'D'))
print(time)
print(time.rolling('3D').mean())

2024-01-01    61
2024-01-02    70
2024-01-03    91
2024-01-04     6
2024-01-05    66
Freq: D, dtype: int64
2024-01-01    61.000000
2024-01-02    65.500000
2024-01-03    74.000000
2024-01-04    55.666667
2024-01-05    54.333333
Freq: D, dtype: float64

<div style = "background-color:lightblue; color:green">This is time based rolling. Instead of last three rows it calculates based on last three days.

In [44]:
print(time.ewm(span = 3).mean())

2024-01-01    61.000000
2024-01-02    67.000000
2024-01-03    80.714286
2024-01-04    40.866667
2024-01-05    53.838710
Freq: D, dtype: float64

<div style = "background-color:lightblue; color:green">ewm(exponentially weighted mean) gives more weight to recent values and ensures smoothness.<br>
Overall windows functions ensure smoothness in noisy data, filling gaps and clear detection.