<h1>Pandas Notes</h1>

<div style ="background-color:lightblue; color:green">Pandas is python library used for data analysis and manipulation.<br>
    Pandas is built on top of numpy, it uses numpy ndim arrays as its core data structure.<br>
    The biggest difference is that numpy is designed for working with homogenous numerical data whereas, pandas is designed for working with tabular heterogeneous data.<div>

In [19]:
import numpy as np

import pandas as pd

In [20]:
from pandas import Series,DataFrame

<h2 style="color:blue">1.Pandas Data Structure

<h3 style="color:blue">1.1 Series

In [10]:
obj =Series([1,2,32,4])
print(obj)
obj.index

0     1
1     2
2    32
3     4
dtype: int64

RangeIndex(start=0, stop=4, step=1)

<div style ="background-color:lightblue; color:green">Series is one dimensional array like object consisting of sequence of value of same type (similar to numpy array) and array of data labels called indexes. <div>

In [12]:
obj = Series([1,2,3,4],index=['a','b','c','d'])
print(obj)
obj.index

a    1
b    2
c    3
d    4
dtype: int64

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
obj = Series([2,3,3,5])
obj.index = ['Alpha','Beta','Gamma','Lambda']
obj

Alpha     2
Beta      3
Gamma     3
Lambda    5
dtype: int64

<div style ="background-color:lightblue; color:green">We can also use specific index as data labels<div>

In [15]:
dictionary = {
    'name':'kn',
    'address':'Nepal',
    'contact':'4434'}
obj1 = Series(dictionary)
print(obj1)

name          kn
address    Nepal
contact     4434
dtype: object

<div style ="background-color:lightblue; color:green">A python dictionary can be converted to Series by passing it to the series, the keys work as data labels and values work as values of the series.<div>

In [17]:
obj2 = Series([1,2,3,4],index = ['a','b','c','d'])
obj3 = obj2.to_dict()
print(obj3)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

<div style ="background-color:lightblue; color:green">Similarly, series can be converted to python dictionary using .to_dict() method.<div>

In [22]:
dictionary = {
    'name':'kn',
    'address':'Nepal',
    'contact':'509393'}
newkeys = ['contact','name','email','address']
obj = Series(dictionary,index = newkeys)
obj

contact    509393
name           kn
email         NaN
address     Nepal
dtype: object

<div style ="background-color:lightblue; color:green">While converting dictionary to series the order of keys and its corresponding values is respected. It can be over written as above example. Since email is not present in the dictionary we got NaN which means not a number or missing value.<div>

In [25]:
dictionary = {
    'name':'kn',
    'address':'Nepal',
    'contact':'509393'}
newkeys = ['contact','name','email','address']
obj = Series(dictionary,index = newkeys)
pd.isna(obj)

contact     True
name        True
email      False
address     True
dtype: bool

In [26]:
dictionary = {
    'name':'kn',
    'address':'Nepal',
    'contact':'509393'}
newkeys = ['contact','name','email','address']
obj = Series(dictionary,index = newkeys)
pd.notna(obj)

contact     True
name        True
email      False
address     True
dtype: bool

<div style ="background-color:lightblue; color:green">We can use isna() and notna() methods to locate missing values.<div>

In [29]:
dictionary = {
    'name':'kn',
    'address':'Nepal',
    'contact':'509393'}
newkeys = ['contact','name','email','address']
obj = Series(dictionary,index = newkeys)
obj.name = 'Details'
obj.index.name = 'Keys'
obj

Keys
contact    509393
name           kn
email         NaN
address     Nepal
Name: Details, dtype: object

<div style ="background-color:lightblue; color:green">Name and index.name attributes can be used to give name to the overall series and data labels.<div>

<h3 style = 'color:blue'>1.2 DataFrames

<div style ="background-color:lightblue; color:green">DataFrames are two dimensional labeled data structure consitining fo rows and columns.It can be thought as dictionary of series.<div>

In [33]:
data = {
    'names':['alpha','beta','gamma','lambda'],
    'ranks':[1,2,3,4],
    'salary':[20000,30000,40000,50000]
}
frame = DataFrame(data)
frame

    names  ranks  salary
0   alpha      1   20000
1    beta      2   30000
2   gamma      3   40000
3  lambda      4   50000

<div style ="background-color:lightblue; color:green">The resulting dataframe will have its index assigned automatically as of series.<div>

In [36]:
data = {
    'name':['alpha','beta','gamma','lambda','juli','rita'],
    'ranks':[1,2,3,4,5,6],
    'salary':[x*10000 for x in range(1,7)]}
frame = DataFrame(data,columns = ['ranks','name','salary'])
frame

   ranks    name  salary
0      1   alpha   10000
1      2    beta   20000
2      3   gamma   30000
3      4  lambda   40000
4      5    juli   50000
5      6    rita   60000

In [37]:
frame.head()

   ranks    name  salary
0      1   alpha   10000
1      2    beta   20000
2      3   gamma   30000
3      4  lambda   40000
4      5    juli   50000

In [38]:
frame.tail()

   ranks    name  salary
1      2    beta   20000
2      3   gamma   30000
3      4  lambda   40000
4      5    juli   50000
5      6    rita   60000

<div style ="background-color:lightblue; color:green">We can also specify the order of columns. head() method gives the first five rows and tail()gives last five rows of data.<div>

In [39]:
data = {
    'name':['alpha','beta','gamma','lambda','juli','rita'],
    'ranks':[1,2,3,4,5,6],
    'salary':[x*10000 for x in range(1,7)]}
frame['name']
frame.ranks

0    1
1    2
2    3
3    4
4    5
5    6
Name: ranks, dtype: int64

<div style ="background-color:lightblue; color:green">Columns in data frame can be retrived as series which can be accessed by either dataframe[column] or dataframe.column way.<div>

In [48]:
data = {
    'name':['alpha','beta','gamma','lambda','juli','rita'],
    'ranks':[1,2,3,4,5,6],
    'salary':[x*10000 for x in range(1,7)]}
frame = DataFrame(data,columns = ['name','ranks','salary','value'])
print(frame)
print("============================")
frame['value'] = 'top'
print(frame)

     name  ranks  salary value
0   alpha      1   10000   NaN
1    beta      2   20000   NaN
2   gamma      3   30000   NaN
3  lambda      4   40000   NaN
4    juli      5   50000   NaN
5    rita      6   60000   NaN
============================
     name  ranks  salary value
0   alpha      1   10000   top
1    beta      2   20000   top
2   gamma      3   30000   top
3  lambda      4   40000   top
4    juli      5   50000   top
5    rita      6   60000   top

<div style ="background-color:lightblue; color:green">The missing columns can be assigned with any values as given above.<div>

In [49]:
data = {
    'name':['alpha','beta','gamma','lambda','juli','rita'],
    'ranks':[1,2,3,4,5,6],
    'salary':[x*10000 for x in range(1,7)]}
frame = DataFrame(data,columns = ['name','ranks','salary'])
frame

     name  ranks  salary
0   alpha      1   10000
1    beta      2   20000
2   gamma      3   30000
3  lambda      4   40000
4    juli      5   50000
5    rita      6   60000

In [52]:
frame['values'] = frame['ranks']
frame
del frame['values']
frame

     name  ranks  salary
0   alpha      1   10000
1    beta      2   20000
2   gamma      3   30000
3  lambda      4   40000
4    juli      5   50000
5    rita      6   60000

<div style ="background-color:lightblue; color:green">We can also add new columns in the above way and delete column using del .<div>

<h3 style = "color:blue">1.3 Dictionary of dictionary as dataframe</h3>

In [54]:
data = {
    'alpha':{'rank':1,'salary':20000,'value':'top'},
    'beta':{'rank':2, 'salary':10000}
}
frame = DataFrame(data)
frame

        alpha     beta
rank        1      2.0
salary  20000  10000.0
value     top      NaN

In [55]:
frame.T

      rank   salary value
alpha    1    20000   top
beta   2.0  10000.0   NaN

In [56]:
frame.T

      rank   salary value
alpha    1    20000   top
beta   2.0  10000.0   NaN

<div style ="background-color:lightblue; color:green"> We can transpose the frame using .T method.<div>

<h3 style = "color:blue">1.4 Possible data input to DataFrame

In [60]:
frame = DataFrame([[1,2,3],
                   [4,5,6]])
frame

   0  1  2
0  1  2  3
1  4  5  6

In [68]:
dicti = {'list1':[1,2,3],
         'list2':[4,5,5]}
frame = DataFrame(dicti)
frame

   list1  list2
0      1      4
1      2      5
2      3      5

In [66]:
listoflist = [[1,2,3],[4,5,6],[7,78,8]]
frame = DataFrame(listoflist)
frame.index.name = "Order of indices"
frame.columns.name ="Order of column"
frame

Order of column   0   1  2
Order of indices
0                 1   2  3
1                 4   5  6
2                 7  78  8

<div style ="background-color:lightblue; color:green">We can also give name to indices and columns using .index.name and .columns.name methods.<div>

In [70]:
frame = DataFrame({'name':['kn','bn','cn'],
                   'rank':[1,2,3]})

frame

  name  rank
0   kn     1
1   bn     2
2   cn     3

In [71]:
frame.to_numpy()

array([['kn', 1],
       ['bn', 2],
       ['cn', 3]], dtype=object)

<div style ="background-color:lightblue; color:green">We can convert dataframes to numpy array using to_numpy() method. The resulting array will be of two dimension containing the data in the dataFrame, according to the order of index.<div>

<h2 style="color:blue">2. Index Object

In [80]:
dicti={
    'name':['kn','bn','cn'],
    'rank':[1,2,3]}
frame = DataFrame(dicti,columns=['rank','name'],index = ['first','second','third'])
print(frame.index)
print(frame.columns)
#index[1] = 'k' #typeerror

Index(['first', 'second', 'third'], dtype='object')
Index(['rank', 'name'], dtype='object')

<div style ="background-color:lightblue; color:green">In pandas index objects are like label system for rows and sometimes columns. They are immutable.<div>

<h3 style="color:blue">2.1 Some index methods and properties</h3>

In [103]:
df1 = pd.DataFrame({'A':[1,2]}, index=['x1','x2'])
df2 = pd.DataFrame({'A':[3,4]}, index=['x2','x3'])

print(df1.index.union(df2.index))         # Index(['x1','x2','x3'], dtype='object')
print(df1.index.intersection(df2.index))  # Index(['x2'], dtype='object')
print(df1.index.difference(df2.index))    # Index(['x1'], dtype='object')
print(df1.index.unique())

Index(['x1', 'x2', 'x3'], dtype='object')
Index(['x2'], dtype='object')
Index(['x1'], dtype='object')
Index(['x1', 'x2'], dtype='object')

<h2 style="color:blue">3. Interacting with data contained in Series and DataFrames

<h3 style="color:blue">3.1 Reindexing Series

In [21]:
series = Series([4,3,522,52,2],index =['b','d','a','c','e'])
series

b      4
d      3
a    522
c     52
e      2
dtype: int64

In [22]:
newindex = ['a','b','c','d','e']
series.index = newindex
print(series)                             #This way only the order of index changes and values remains as it is

#If we want to change the order of index with their corresponding values, we can use reindex

series.reindex(['d','a','b','e','c'])
print("=========================")

print(series)

a      4
b      3
c    522
d     52
e      2
dtype: int64
=========================
a      4
b      3
c    522
d     52
e      2
dtype: int64

<div style ="background-color:lightblue; color:green">We can use reindex if we want to change the order of indices and also keep the original order of values corrponding to the indices.<div>

In [111]:
series1 = Series(['alpha','beta','gamma'],index = [0,2,4])
print(series1)

0    alpha
2     beta
4    gamma
dtype: object

In [113]:
# series2 = series.reindex(np.arange(6))
# print(series2)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
dtype: float64

In [121]:
print(series1.reindex(np.arange(6),method = "ffill"))

0    alpha
1    alpha
2     beta
3     beta
4    gamma
5    gamma
dtype: object

<div style ="background-color:lightblue; color:green">ffill that is forward fill repeates the last known value to next unknown value.<div>

<h3 style="color:blue"> 3.2 Reindexing DataFrame

In [124]:
frame = DataFrame(np.arange(9).reshape(3,3),index = ['a','b','c'],columns = ['first','second','third'])
frame

   first  second  third
a      0       1      2
b      3       4      5
c      6       7      8

In [126]:
frame2 = frame.reindex(index = ['c','a','b'])    # Or, frame.reindex(['c','a','b'],axis = rows)
print(frame2)

   first  second  third
c      6       7      8
a      0       1      2
b      3       4      5

In [127]:
frame3 = frame.reindex(columns = ['third','second','first'])    # Or, frame,reindex(newindex,axis = columns)
print(frame3)

   third  second  first
a      2       1      0
b      5       4      3
c      8       7      6

<div style ="background-color:lightblue; color:green">For dataframes we can reindex either by row axis or column axis.<div>

<h2 style="color:blue">4. Dropping Entries from the axis

In [128]:
series = Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [130]:
del series['a']

In [131]:
print(series)

b    2
c    3
d    4
e    5
dtype: int64

In [133]:
newseries = series.drop('c')
print(newseries)

b    2
d    4
e    5
dtype: int64

<div style ="background-color:lightblue; color:green">We can delete entries from the series using both del and .drop method. But, we commonly used.drop because it can delete more than one enteries and one, also it is consistent with data frames.<div>

In [135]:
frame = DataFrame(np.arange(16).reshape(4,4),index = ['a','b','c','d'],columns = ['first','second','third','fourth'])
print(frame)

   first  second  third  fourth
a      0       1      2       3
b      4       5      6       7
c      8       9     10      11
d     12      13     14      15

In [139]:
frame1 = frame.drop(['a'],axis = 'rows')  #or frame.drop(['a'],axis = 'index') or, frame.drop(index = ['a'])
print(frame1)

   first  second  third  fourth
b      4       5      6       7
c      8       9     10      11
d     12      13     14      15

In [143]:
frame2 = frame1.drop(['third'],axis = 1) # or frame.drop(['first', axis = 'columns']) or, frame.drop(columns = ['first']
print(frame2)

   first  second  fourth
b      4       5       7
c      8       9      11
d     12      13      15

<h2 style="color:blue">5. Indexing, Selecting and Filtering</h2>

<h3 style = "color:blue">5.1 For Series</h3>

In [144]:
series = Series([1,2,3,4],index = ['a','b','c','d'])
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [148]:
print(series['b'])

2

In [149]:
print(series[1:3])

b    2
c    3
dtype: int64

In [151]:
series.index = [0,1,2,3]
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [152]:
print(series[1])

2

<div style ="background-color:lightblue; color:green">Here we can select data from series using normal slicing with index but, it create confusion with the data labels are integers. For example if data label is series['a'] it works fine with no confusion but, when data labels are integers that is series[1] then it creates confusion that 1 is label or position of row, in this case it is label. So while slicing for series or dataframes, we commonly use .loc and .iloc methods.<div>

In [174]:
series = Series(np.arange(4),index = ['a','b','c','d'])
print(series)

a    0
b    1
c    2
d    3
dtype: int64

In [177]:
print(series.loc[['a','d']])
print(series.loc['c'])
print(series.loc['a':'d'])

a    0
d    3
dtype: int64
2
a    0
b    1
c    2
d    3
dtype: int64

<div style ="background-color:lightblue; color:green">.loc works similary to normal python slicing, the only difference is that the end point is inclusive. The values inside .loc only indicate the labels creating no confusion. .loc can take single label, list of labels or slice.<div>

In [178]:
series = Series(['First','Second','Third','Fourth','Fifth','Sixth'])
print(series)

0     First
1    Second
2     Third
3    Fourth
4     Fifth
5     Sixth
dtype: object

In [181]:
print(series.iloc[2:4])
print(series.iloc[[2,3,4]])
print(series.iloc[3])

2     Third
3    Fourth
dtype: object
2     Third
3    Fourth
4     Fifth
dtype: object
Fourth

<div style ="background-color:lightblue; color:green">We specially use .iloc when the labels are integers. It can also take single label, list of labels or slice(but this time end point is exclusive).<div>

<h3 style="color:blue">5.2 For DataFrame</h3>

In [184]:
frame = DataFrame(np.arange(9).reshape(3,3),index = ['First','Second','Third'],columns = ['A','B','C'])
print(frame)

        A  B  C
First   0  1  2
Second  3  4  5
Third   6  7  8

In [187]:
print(frame['A'])

First     0
Second    3
Third     6
Name: A, dtype: int64

In [189]:
print(frame[[
    'B','C']])

        B  C
First   1  2
Second  4  5
Third   7  8

In [191]:
print(frame[frame['C'] > 4])

        A  B  C
Second  3  4  5
Third   6  7  8

<div style ="background-color:lightblue; color:green">Indexing into dataframe retrives various columns either by passing single value, array of values or boolean conditioning. This type of normal selection with dataframe specially works for its columns only. Using .loc and .iloc give more control over both rows and columns<div>

In [193]:
data = DataFrame(np.arange(16).reshape(4,4),index = ['First','Second','Third','Fourth'],columns = ['Alpha','Beta','Gamma','Lambda'])
print(data)

        Alpha  Beta  Gamma  Lambda
First       0     1      2       3
Second      4     5      6       7
Third       8     9     10      11
Fourth     12    13     14      15

In [194]:
print(data.loc['First'])

Alpha     0
Beta      1
Gamma     2
Lambda    3
Name: First, dtype: int64

In [196]:
print(data.loc[['First','Third']])

       Alpha  Beta  Gamma  Lambda
First      0     1      2       3
Third      8     9     10      11

<div style ="background-color:lightblue; color:green">.loc (label indexing) helps to retrive one or more rows with its columns .<div>

In [230]:
data = DataFrame(np.arange(16).reshape(4,4), index = ['First','Second','Third','Fourth'], columns = [ 'Alpha','Beta','Gamma','Juli'])
print(data)

        Alpha  Beta  Gamma  Juli
First       0     1      2     3
Second      4     5      6     7
Third       8     9     10    11
Fourth     12    13     14    15

In [232]:
print(data.loc['First',['Alpha','Juli']])
print(data.loc['First':'Third'])

Alpha    0
Juli     3
Name: First, dtype: int64
        Alpha  Beta  Gamma  Juli
First       0     1      2     3
Second      4     5      6     7
Third       8     9     10    11

<div style ="background-color:lightblue; color:green">We can also select row and specific columns by using comma and passing two arguments for both rows and columns. We should not be confused with rows and columns as .loc is label based indexing , so it takes label of rows and columns as argument for selection. Slicing is similar to slicing in series with both start and end point inclusive.<div>

In [219]:
data = DataFrame({'First':['a','b','c'],
                  'Second':['d','e','f'],
                  'Third':['g','h','i']})
print(data)

  First Second Third
0     a      d     g
1     b      e     h
2     c      f     i

In [220]:
print(data.iloc[1])

First     b
Second    e
Third     h
Name: 1, dtype: object

In [233]:
print(data.iloc[[1,2]])

        Alpha  Beta  Gamma  Juli
Second      4     5      6     7
Third       8     9     10    11

In [215]:
print(data.iloc[[1,2],[2]])

  Third
1     h
2     i

<div style ="background-color:lightblue; color:green">Since .iloc only takes integer indexes if the column is not integers, we need to use normal indexing that is (n-1) method to select each columns .<div>

In [234]:
print(data.iloc[0:2])

        Alpha  Beta  Gamma  Juli
First       0     1      2     3
Second      4     5      6     7

<div style ="background-color:lightblue; color:green">Slicing with iloc similar to how we did we series with end point exclusive.<div>

<h2 style="color:blue">6. Arithmetic and Data alignment</h2>

<h3 style="color:blue">6.1 Data alignment in series and dataframes</h2>

In [7]:
s1 = Series([1,2,3,4],index = ['a','b','c','d'])
s2 = Series([4,3,2,5,2,5], index = ['d','b','g','i','c','a'])
print(s1+s2)

a    6.0
b    5.0
c    5.0
d    8.0
g    NaN
i    NaN
dtype: float64

<div style="background-color:lightblue; color:green">When we perform arithmetic on two objects of different arrangement of index then the resulting object will have the union of indexes of those two objects. The value of only those indexes that are common in both will be obtained and others will be NaN.</div>

In [12]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = ['One','Three','Five'])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = ['Three','Four','Two','One'])
print(df1)
print("=========================")
print(df2)
print("=========================")
print(df1+df2)

   One  Three  Five
a    0      1     2
c    3      4     5
d    6      7     8
=========================
   Three  Four  Two  One
b      0     1    2    3
a      4     5    6    7
g      8     9   10   11
=========================
   Five  Four  One  Three  Two
a   NaN   NaN  7.0    5.0  NaN
b   NaN   NaN  NaN    NaN  NaN
c   NaN   NaN  NaN    NaN  NaN
d   NaN   NaN  NaN    NaN  NaN
g   NaN   NaN  NaN    NaN  NaN

In [17]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])
print(df1)
print("=========================")
print(df2)
print("=========================")
print(df1+df2)

   1  3  5
a  0  1  2
c  3  4  5
d  6  7  8
=========================
   3  4   2   1
b  0  1   2   3
a  4  5   6   7
g  8  9  10  11
=========================
     1   2    3   4   5
a  7.0 NaN  5.0 NaN NaN
b  NaN NaN  NaN NaN NaN
c  NaN NaN  NaN NaN NaN
d  NaN NaN  NaN NaN NaN
g  NaN NaN  NaN NaN NaN

<div style="background-color:lightblue; color:green">Alignment works on the basis of data labels. The resulting object will have the indexes as the union of index pairs of two dataframes. After union they are arraned on the basis of alphabetical order and only values of common data labels  are obtained and other remains NaN.</div>

<h3 style="color:blue">6.2 Filling value for NaN</h3>

In [18]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])
print(df1)
print("=========================")
print(df2)
print("=========================")
print(df1+df2)

   1  3  5
a  0  1  2
c  3  4  5
d  6  7  8
=========================
   3  4   2   1
b  0  1   2   3
a  4  5   6   7
g  8  9  10  11
=========================
     1   2    3   4   5
a  7.0 NaN  5.0 NaN NaN
b  NaN NaN  NaN NaN NaN
c  NaN NaN  NaN NaN NaN
d  NaN NaN  NaN NaN NaN
g  NaN NaN  NaN NaN NaN

In [21]:
df3 = df1+df2
# df3[df3.isna()] = 10
print(df3.fillna(10))

      1     2     3     4     5
a   7.0  10.0   5.0  10.0  10.0
b  10.0  10.0  10.0  10.0  10.0
c  10.0  10.0  10.0  10.0  10.0
d  10.0  10.0  10.0  10.0  10.0
g  10.0  10.0  10.0  10.0  10.0

<div style="background-color:lightblue; color:green">We can simply assign a specific value to the resulting object with NaN using boolean conditioning and .isna() or fillna() method. There is also another way to perform same operation.</div>

In [20]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])
print(df1.add(df2,fill_value = 10))

      1     2     3     4     5
a   7.0  16.0   5.0  15.0  12.0
b  13.0  12.0  10.0  11.0   NaN
c  13.0   NaN  14.0   NaN  15.0
d  16.0   NaN  17.0   NaN  18.0
g  21.0  20.0  18.0  19.0   NaN

<div style="background-color:lightblue; color:green">fill_value argument is passed to add method along with another object. It helps to assign value in the resulting object if atleast one value is not present in one of the object. If the value is not present in both then the resultig object will still have NaN. If you want to completely replace Nan with some value you can use .isna() or fillna() methods as explained above.</div>

<h3 style="color:blue">6.3 Some arithmetic methods and their counter part</h3>

In [ ]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])

In [22]:
print(df1)

   1  3  5
a  0  1  2
c  3  4  5
d  6  7  8

In [23]:
print(df2)

   3  4   2   1
b  0  1   2   3
a  4  5   6   7
g  8  9  10  11

In [24]:
print(df1.add(df2,fill_value = 0))

      1     2    3    4    5
a   7.0   6.0  5.0  5.0  2.0
b   3.0   2.0  0.0  1.0  NaN
c   3.0   NaN  4.0  NaN  5.0
d   6.0   NaN  7.0  NaN  8.0
g  11.0  10.0  8.0  9.0  NaN

In [25]:
print(df1.radd(df2,fill_value = 0))

      1     2    3    4    5
a   7.0   6.0  5.0  5.0  2.0
b   3.0   2.0  0.0  1.0  NaN
c   3.0   NaN  4.0  NaN  5.0
d   6.0   NaN  7.0  NaN  8.0
g  11.0  10.0  8.0  9.0  NaN

<div style="background-color:lightblue; color:green">Here .add() simply works as df1+df2 will fill_value as argument to work with missing value. radd() workds as df2+df1, for add they might look same but for other arithmetic operations such as subtract and division it create a lot of difference.</div>

In [26]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])
print(df1)

   1  3  5
a  0  1  2
c  3  4  5
d  6  7  8

In [27]:
print(df2)

   3  4   2   1
b  0  1   2   3
a  4  5   6   7
g  8  9  10  11

In [28]:
print(df1.sub(df2,fill_value = 0))

      1     2    3    4    5
a  -7.0  -6.0 -3.0 -5.0  2.0
b  -3.0  -2.0  0.0 -1.0  NaN
c   3.0   NaN  4.0  NaN  5.0
d   6.0   NaN  7.0  NaN  8.0
g -11.0 -10.0 -8.0 -9.0  NaN

In [30]:
print(df1.rsub(df2,fill_value = 0))

      1     2    3    4    5
a   7.0   6.0  3.0  5.0 -2.0
b   3.0   2.0  0.0  1.0  NaN
c  -3.0   NaN -4.0  NaN -5.0
d  -6.0   NaN -7.0  NaN -8.0
g  11.0  10.0  8.0  9.0  NaN

<div style="background-color:lightblue; color:green">Here you can clearly see the difference between sub and rsub methods. sub works as df1-df2 and rsub works as df2-df1.</div>

In [31]:
df1 = DataFrame(np.arange(9).reshape((3,3)),index = list('acd'),columns = [1,3,5])
df2 = DataFrame(np.arange(12).reshape((3,4)), index = list('bag'),columns = [3,4,2,1])
print(df1)
print("======================")
print(df2)

   1  3  5
a  0  1  2
c  3  4  5
d  6  7  8
======================
   3  4   2   1
b  0  1   2   3
a  4  5   6   7
g  8  9  10  11

In [32]:
print(df1.div(df2,fill_value = 0))

     1    2     3    4    5
a  0.0  0.0  0.25  0.0  inf
b  0.0  0.0   NaN  0.0  NaN
c  inf  NaN   inf  NaN  inf
d  inf  NaN   inf  NaN  inf
g  0.0  0.0  0.00  0.0  NaN

In [33]:
print(df1.rdiv(df2,fill_value = 0))

     1    2    3    4    5
a  inf  inf  4.0  inf  0.0
b  inf  inf  NaN  inf  NaN
c  0.0  NaN  0.0  NaN  0.0
d  0.0  NaN  0.0  NaN  0.0
g  inf  inf  inf  inf  NaN

In [35]:
print(df1.pow(df2,fill_value = 0))

     1    2    3    4    5
a  0.0  0.0  1.0  0.0  1.0
b  0.0  0.0  1.0  0.0  NaN
c  1.0  NaN  1.0  NaN  1.0
d  1.0  NaN  1.0  NaN  1.0
g  0.0  0.0  0.0  0.0  NaN

In [36]:
print(df1.rpow(df2,fill_value=0))

     1    2    3    4    5
a  1.0  1.0  4.0  1.0  0.0
b  1.0  1.0  1.0  1.0  NaN
c  0.0  NaN  0.0  NaN  0.0
d  0.0  NaN  0.0  NaN  0.0
g  1.0  1.0  1.0  1.0  NaN

<h2 style="color:blue">7. Operations between Series and DataFrames</h2>

In [43]:
twoD = np.array(np.arange(12).reshape((3,4)))
print(twoD)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [45]:
oneD = twoD[1]
oneD

array([4, 5, 6, 7])

In [46]:
print(twoD - oneD)

[[-4 -4 -4 -4]
 [ 0  0  0  0]
 [ 4  4  4  4]]

<div style="background-color:lightblue; color:green">First as an example we can subtract two numpy arrays of different size and dimension using the rules of broadcasting.</div>

In [4]:
frame = DataFrame(np.arange(12).reshape((3,4)),columns = list('abcd'),index= ['Apple','Ball','Cat'])
print(frame)
print("=====================")
series = frame.iloc[0]
print(series)

       a  b   c   d
Apple  0  1   2   3
Ball   4  5   6   7
Cat    8  9  10  11
=====================
a    0
b    1
c    2
d    3
Name: Apple, dtype: int64

In [67]:
print(frame - series)

       a  b  c  d
Apple  0  0  0  0
Ball   4  4  4  4
Cat    8  8  8  8

<div style="background-color:lightblue; color:green">Here, the index of series aligns with the column of data frame, the series is subtracted from each row of dataframe.</div>

In [72]:
frame2 = DataFrame(np.arange(12).reshape((3,4)), columns = list('abcd'), index = ['Apple','Ball','Cat'])
series2 = Series(np.arange(3), index = list('bcf'))

In [73]:
print(frame2)

       a  b   c   d
Apple  0  1   2   3
Ball   4  5   6   7
Cat    8  9  10  11

In [74]:
print(series2)

b    0
c    1
f    2
dtype: int64

In [83]:
print(frame2.sub(series2, axis = 1))  #axis = 0, braodcast over column matching on the row

        a    b    c   d   f
Apple NaN  1.0  1.0 NaN NaN
Ball  NaN  5.0  5.0 NaN NaN
Cat   NaN  9.0  9.0 NaN NaN

<div style="background-color:lightblue; color:green">If the index value is not found in either the series's index or dataframe's column then the resulting object will have the union of index of both the objects. And only those index that are common in both will have the value.</div>

<h2 style="color:blue">8. Function Application and Mapping</h2>

In [110]:
def f1(x):
    return x.max()-x.min()
series = Series(np.arange(5),index=['a','b','c','d','e'])
frame = DataFrame(np.arange(12).reshape((3,4)),index = ['a','b','c'],columns=['First','Second','Third','Fourth'])
print(frame)

   First  Second  Third  Fourth
a      0       1      2       3
b      4       5      6       7
c      8       9     10      11

In [111]:
print(series)

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [112]:
print(f1(frame))

First     8
Second    8
Third     8
Fourth    8
dtype: int64

In [113]:
print(f1(series))

4

<div style="background-color:lightblue; color:green">While we can also pass series or dataframe as argument in normal python user defined function,using pandas methods such as map(), apply() and applymap() are considered to be used for series and dataframes. They are fast and efficient compared to normal python functions. By directly passing series or dataframe to user defined function it performs operation element wise one by one, which is not efficient. Pandas method adopts the methods of vectorized operation and performs operation on entire elemet of array at once.</div>

<h3 style="color:blue">8.1 Using .map() method

<div style="background-color:lightblue; color:green">Mapping is the process transforming pandas objects by replacing values of series or dataframe columns according defined conditions.</div>

In [ ]:
series = Series(np.arange(6),index=list('abcdef'))

In [114]:
print(series)

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [116]:
mapped_series = series.map(lambda x: x**2)
print(mapped_series)

a     0
b     1
c     4
d     9
e    16
dtype: int64

<div style="background-color:lightblue; color:green">.map() methods takes a function as argument and apply it to the series and transform it which is called mapping. Here, map is used to series object. It can take series, functions or dictionary for mapping.</div>

In [117]:
series = Series(['B','C','A','E','D'])
map_dict = {
    'A':'Excellent',
    'B':'VeryGood',
    'C':'Good',
    'D':'Bad',
    'E':'BetterLuckNextTime'
}
mapped_series = series.map(map_dict)
print(mapped_series)

0              VeryGood
1                  Good
2             Excellent
3    BetterLuckNextTime
4                   Bad
dtype: object

<div style="background-color:lightblue; color:green">we can even use dictionary or series for mapping.</div>

In [12]:
df = DataFrame({
    'Gender':['Male','Female','Female','Male','Female'],
    'Experience':[2,4,2,5,4],
    'Salary':[x*1000 for x in range(1,6)]
})

Gender_mapper = {'Male':'M',
                 'Female':'F'}

df['Gender'] = df['Gender'].map(Gender_mapper)
print(df)

  Gender  Experience  Salary
0      M           2    1000
1      F           4    2000
2      F           2    3000
3      M           5    4000
4      F           4    5000

<h2 style=

<h3 style="color:blue">8.2 Using .apply()</h3>

<div style="background-color:lightblue;color:green">.apply() function is used to apply other function along any axis of a dataframe.</div>

In [14]:
df = DataFrame({
    'Gender':['Male','Female','Female','Male','Female'],
    'Experience_Work':[2,4,2,5,4],
    'Experience_Business':[2,3,2,5,2],
    'Salary':[x*1000 for x in range(1,6)]
})
print(df)

   Gender  Experience_Work  Experience_Business  Salary
0    Male                2                    2    1000
1  Female                4                    3    2000
2  Female                2                    2    3000
3    Male                5                    5    4000
4  Female                4                    2    5000

In [19]:
def expadder(row):
    total_exp = row['Experience_Work']+row['Experience_Business']
    return total_exp

df.apply(expadder,axis = 1)

0     4
1     7
2     4
3    10
4     6
dtype: int64

<div style="background-color:lightblue; color:green"> In the above example, we have dataset for persons categorized by their gender and their experience in work and business. First we defined a normal python function that will take inputs from each rows(Experience_Work and Experience_Busiiness) of the dataframe and add them to give overall experience. We used apply function to apply this function to each row of the data frame or along axis = 1. </div>

<h2 style="color:blue">9. Ranking and Sorting</h2>

<h3 style="color:blue"> 9.1 Sorting Series

In [9]:
Obj = Series(np.array(['First','Second','Third','Fourth']), index = list('dbac'))
print(Obj)

d     First
b    Second
a     Third
c    Fourth
dtype: object

In [10]:
print(Obj.sort_index())

a     Third
b    Second
c    Fourth
d     First
dtype: object

<div style="background-color:lightblue; color:green">sort_index() method return new sorted series on the basis of its index. While sorting on the basis of index the data corresponding to particular index also move with the new position. To sort the series by its values, we use sort_values method.</div>

In [25]:
Obj = Series([1,2,552,45,252,525,2,33,23],index = list('fgecgekec'))
print(Obj)

f      1
g      2
e    552
c     45
g    252
e    525
k      2
e     33
c     23
dtype: int64

In [26]:
print(Obj.sort_index())

c     45
c     23
e    552
e    525
e     33
f      1
g      2
g    252
k      2
dtype: int64

In [27]:
print(Obj.sort_values())

f      1
g      2
k      2
c     23
e     33
c     45
g    252
e    525
e    552
dtype: int64

<h3 style="color:blue">9.2 Sorting Dataframe</h3>

In [28]:
frame = DataFrame(np.random.randint(0,20, size=(4,5)), index = list('gecd'), columns = ['Second', 'Fourth', 'First', 'Fifth','Third'])
print(frame)

   Second  Fourth  First  Fifth  Third
g       2      19     10      6      0
e       6       1      0     14     10
c       4       3      7     17     12
d      15      18      3      1     10

In [29]:
print(frame.sort_index())

   Second  Fourth  First  Fifth  Third
c       4       3      7     17     12
d      15      18      3      1     10
e       6       1      0     14     10
g       2      19     10      6      0

In [30]:
print(frame.sort_index(axis=1))

   Fifth  First  Fourth  Second  Third
g      6     10      19       2      0
e     14      0       1       6     10
c     17      7       3       4     12
d      1      3      18      15     10

<div style="background-color:lightblue; color:green">This is how we can sort the dataframe by both the axis in the lexicographically order. BY default the sorting works on ascending order, it can be changed by passing the ascending = 'false' argument as shown below.</div>

In [39]:
frame = DataFrame(np.arange(0,10).reshape(2,5), index = list('ab'), columns = list('bdace'))
print(frame)

   b  d  a  c  e
a  0  1  2  3  4
b  5  6  7  8  9

In [40]:
print(frame.sort_index(axis = 1, ascending = False))

   e  d  c  b  a
a  4  1  3  0  2
b  9  6  8  5  7

In [41]:
print(frame.sort_values(by = 'a'))

   b  d  a  c  e
a  0  1  2  3  4
b  5  6  7  8  9

In [42]:
print(frame.sort_values(by = 'd'))

   b  d  a  c  e
a  0  1  2  3  4
b  5  6  7  8  9

<div style="background-color:lightblue; color:green">.sort_values() method takes the columns name as by argument and sorts the dataframe according to its values.</div>

In [12]:
obj = Series([2,4,5,2,4,8], index=list('abcdef'))
print(obj)

a    2
b    4
c    5
d    2
e    4
f    8
dtype: int64

In [14]:
print(obj.rank())

a    1.5
b    3.5
c    5.0
d    1.5
e    3.5
f    6.0
dtype: float64

<div style="background-color:lightblue; color:green">Ranking is the process of assigning ranks to the values of objects starting from lowest. Ties values get mean rank. 2 has the ranks 1,2, so it got the mean rank that is (1+2)/2.</div>

In [15]:
print(obj.rank(ascending = False))

a    5.5
b    3.5
c    2.0
d    5.5
e    3.5
f    1.0
dtype: float64

<div style="background-color:lightblue; color:green">In descending order the lowest value gets the highest rank.

<div style="background-color:lightblue; color:green">There are various methods for ties values while assinging ranks using .rank() method.

In [34]:
obj = Series([2,4,7,2,9,4,2], index = list('abcedfg'))
print(obj)

a    2
b    4
c    7
e    2
d    9
f    4
g    2
dtype: int64

In [35]:
print(obj.rank())

a    2.0
b    4.5
c    6.0
e    2.0
d    7.0
f    4.5
g    2.0
dtype: float64

In [36]:
print(obj.rank(method = 'first'))

a    1.0
b    4.0
c    6.0
e    2.0
d    7.0
f    5.0
g    3.0
dtype: float64

<div style="background-color:lightblue; color:green">This time instead of using mean rank for the ties value, the rank has been assinged on the basis of their appearance.

In [37]:
print(obj.rank(method = 'min'))

a    1.0
b    4.0
c    6.0
e    1.0
d    7.0
f    4.0
g    1.0
dtype: float64

<div style="background-color:lightblue; color:green">This time the ties value got the minimum rank among them.

In [38]:
print(obj.rank(method = 'max'))

a    3.0
b    5.0
c    6.0
e    3.0
d    7.0
f    5.0
g    3.0
dtype: float64

<div style="background-color:lightblue; color:green">Similarly, we can use max to assign max rank to break the tie.

In [39]:
print(obj.rank(method = 'dense'))

a    1.0
b    2.0
c    3.0
e    1.0
d    4.0
f    2.0
g    1.0
dtype: float64

<div style="background-color:lightblue; color:green">dense method work similar to min method but, this time without any gap.

In [40]:
obj = DataFrame(np.random.randint(1,21, size = (4,5)), index = list('abcd'), columns = ['First','Second','Third','Fourth','Fifth'])
print(obj)

   First  Second  Third  Fourth  Fifth
a      5      10     15       2     19
b     14       4      6      14     20
c     19      14      8      18     16
d     10       9      4      20     12

In [45]:
print(obj.rank())
print('\n')
print(obj.rank( axis = 1))

   First  Second  Third  Fourth  Fifth
a    1.0     3.0    4.0     1.0    3.0
b    3.0     1.0    2.0     2.0    4.0
c    4.0     4.0    3.0     3.0    2.0
d    2.0     2.0    1.0     4.0    1.0


   First  Second  Third  Fourth  Fifth
a    2.0     3.0    4.0     1.0    5.0
b    3.5     1.0    2.0     3.5    5.0
c    5.0     2.0    1.0     4.0    3.0
d    3.0     2.0    1.0     5.0    4.0

<h2 style="color:blue">10. Mathematical and Statistical Methods</h2>

In [16]:
df = DataFrame(np.random.randint(1,100, size = (4,5)), index = list('abcd'), columns = ['First','Second','Third','Fourth','Fifth'])
print(df)

   First  Second  Third  Fourth  Fifth
a     93      11     60       8     52
b     19      98     62      14     53
c     33      78     58      69     61
d     13       9     69      89     40

In [17]:
print(df.sum())

First     158
Second    196
Third     249
Fourth    180
Fifth     206
dtype: int64

In [18]:
print(df.sum(axis = 1))

a    224
b    246
c    299
d    220
dtype: int64

In [22]:
df = DataFrame([[1,2,np.nan,4],[np.nan,np.nan,np.nan,np.nan],[3,6,4,np.nan],[3,5,3,3]],columns =['First','Second','Third','Fourth'],index = list('abcd'))
print(df)

   First  Second  Third  Fourth
a    1.0     2.0    NaN     4.0
b    NaN     NaN    NaN     NaN
c    3.0     6.0    4.0     NaN
d    3.0     5.0    3.0     3.0

In [24]:
print(df.sum(axis=1))

a     7.0
b     0.0
c    13.0
d    14.0
dtype: float64

<h2 style ="color:blue">11. Corelation and Covariance

<h3 style="color:blue">11.1 Covariance</h3>

In [27]:
obj = Series(np.arange(1,6),index = list('abcde'))
print(obj)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [39]:
obj2 = Series(np.arange(1,6), index = list('abcde'))
print(obj2)

obj3 = obj2.apply(lambda x : x-2)
print(obj3)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a   -1
b    0
c    1
d    2
e    3
dtype: int64

In [40]:
print(obj.cov(obj3))

2.5

In [44]:
df = DataFrame({'Height':[188,192,155,163],
                'Weight':[60,67,80,59]},
                index = ['Person1','Person2','Person3','Person4'])
print(df)

         Height  Weight
Person1     188      60
Person2     192      67
Person3     155      80
Person4     163      59

In [47]:
print(df['Height'].cov(df['Weight']))

-85.33333333333333

<div style ="background-color:lightblue; color:green"> Covariance tells how two quantity changes together. Positive covariance means both quantity increase/decrease together, whereas negative covariance means one increase and other decrease or vice versa.</div>

<h3 style="color:blue">11.2 Corelation</h3>

<div style ="background-color:lightblue; color:green">Corelation measures how strongly and in which direction two variables are related. It is a standarilized form of covariance and is bounded to -1 to +1 depending upon the strength of relation.
</div>

In [44]:
df = DataFrame({'Height':[188,192,155,163],
                'Weight':[60,67,80,59]},
                index = ['Person1','Person2','Person3','Person4'])
print(df)

         Height  Weight
Person1     188      60
Person2     192      67
Person3     155      80
Person4     163      59

In [49]:
print(df['Height'].corr(df['Weight']))

-0.48269162835103746